#!/usr/bin/env python3
"""Generate matmul_iface.v -- flatten the HLS core's per-element ports into
four wide vectors so the UART controller can shift bytes into one register.

    python3 gen_matmul_iface.py 8 > matmul_iface.v

WHY THIS REPLACES THE OLD SCRIPT
The previous generators emitted the instantiation with port names arg0_0_0 /
arg1_0_0 / arg2_0_0, which is what the HLS core exported back when design.cpp
named its parameters arg0/arg1/arg2. The parameters are now A / B / Cinout, so
the core's ports are A_i_j, B_i_j, Cinout_i_j_i, Cinout_i_j_o and
Cinout_i_j_o_ap_vld -- and every generated iface stopped matching. The 4x4
matmul_iface.v checked into gemm_4x4/rtl was evidently hand-patched afterwards,
which is why it works while re-running its own generator does not reproduce it.

Widths are derived from N here rather than written as literals; the old scripts
hard-coded 511/15 for 4x4, so bumping N alone silently produced a file with 8x8
loop bounds and 4x4 port widths.

The internal wire names keep the w_arg0_/w_arg1_/w_arg2_ prefixes: they are
local, and keeping them makes the diff against the existing 4x4 file small.
"""

import sys


def generate(n):
    elems = n * n
    dw = elems * 32                     # flat data width
    L = []
    a = L.append

    a(f"// Auto-generated by gen_matmul_iface.py ({n}x{n}) -- 請勿手動修改")
    a("// Flattens the HLS core's per-element ports into wide vectors.")
    a("module matmul_iface (")
    a("    input  wire        ap_clk,")
    a("    input  wire        ap_rst,")
    a("    input  wire        ap_start,")
    a("    output wire        ap_done,")
    a("    output wire        ap_idle,")
    a("    output wire        ap_ready,")
    a(f"    input  wire [{dw-1}:0] arg0_flat,")
    a(f"    input  wire [{dw-1}:0] arg1_flat,")
    a(f"    input  wire [{dw-1}:0] arg2_in_flat,")
    a(f"    output wire [{dw-1}:0] arg2_out_flat,")
    a(f"    output wire [{elems-1}:0]   arg2_vld_flat")
    a(");")
    a("")

    # --- slice the flat inputs into per-element wires -----------------
    for tag in ("arg0", "arg1", "arg2_in"):
        for i in range(n):
            for j in range(n):
                idx = i * n + j
                hi, lo = idx * 32 + 31, idx * 32
                a(f"    wire [31:0] w_{tag}_{i}_{j} = {tag}_flat[{hi}:{lo}];")
        a("")

    # --- outputs come back as arrays, then get packed ----------------
    a(f"    wire [31:0] w_arg2o   [0:{elems-1}];")
    a(f"    wire        w_arg2vld [0:{elems-1}];")
    a("")
    for i in range(n):
        for j in range(n):
            idx = i * n + j
            hi, lo = idx * 32 + 31, idx * 32
            a(f"    assign arg2_out_flat[{hi}:{lo}] = w_arg2o[{idx}];")
            a(f"    assign arg2_vld_flat[{idx}] = w_arg2vld[{idx}];")
    a("")

    # --- the core ----------------------------------------------------
    # Port names must match the HLS export exactly: A_i_j, B_i_j and the
    # three-way split Cinout_i_j_i / _o / _o_ap_vld.
    a("    matmul_4x4x4 u_matmul (")
    a("        .ap_clk(ap_clk),")
    a("        .ap_rst(ap_rst),")
    a("        .ap_start(ap_start),")
    a("        .ap_done(ap_done),")
    a("        .ap_idle(ap_idle),")
    a("        .ap_ready(ap_ready),")
    for i in range(n):
        for j in range(n):
            a(f"        .A_{i}_{j}(w_arg0_{i}_{j}),")
    for i in range(n):
        for j in range(n):
            a(f"        .B_{i}_{j}(w_arg1_{i}_{j}),")
    conns = []
    for i in range(n):
        for j in range(n):
            idx = i * n + j
            conns.append(f"        .Cinout_{i}_{j}_i(w_arg2_in_{i}_{j})")
            conns.append(f"        .Cinout_{i}_{j}_o(w_arg2o[{idx}])")
            conns.append(f"        .Cinout_{i}_{j}_o_ap_vld(w_arg2vld[{idx}])")
    a(",\n".join(conns))
    a("    );")
    a("")
    a("endmodule")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    sys.stdout.write(generate(n))