#!/usr/bin/env python3
"""Generate matmul_iface_rk.v -- runtime-K interface wrapper, fold-capable.

    python3 gen_matmul_iface_fold_new.py 8 64 1 1 > iface_mt1.v    # legacy
    python3 gen_matmul_iface_fold_new.py 8 64 2 2 > iface_mt2.v    # 4 folds
    python3 gen_matmul_iface_fold_new.py 8 64 8 8 > iface_mt8.v    # 64 folds

    argv: n  kmax  mt  nt
      n     array is n x n
      kmax  max reduction depth per invocation
      mt    max folds along M (blocks of n rows of A)
      nt    max folds along N (blocks of n columns of B)

WHAT THIS ADDS OVER gen_matmul_iface_new.py

The old wrapper held exactly one fold's worth of operands: 8 banks of K_MAX
words for A, likewise for B. A tile bigger than the array therefore had to be
decomposed on the host, one UART round trip per fold, which is where all the
time goes -- the per-fold A and B blocks get re-sent even though most of them
are reused.

This version stores mt (resp. nt) folds' worth and adds two inputs that
select which fold the core currently reads:

    input [fi_w-1:0] fold_i     which block of n rows of A
    input [fj_w-1:0] fold_j     which block of n columns of B

The controller can then walk the fold grid without touching the UART.

*** WHY THE ADDRESSING IS FREE ***

The core drives a clog2(kmax)-bit word address. When kmax is a power of two,

    ram_addr = fold * kmax + word  ==  {fold, word}

so the offset is pure concatenation: no adder, no carry chain, no timing
cost. If you ever set kmax to something that is not a power of two, this
becomes a real multiply-add on the address path and the assumption above
silently stops holding. There is an assert for it below.

*** BRAM COST IS ZERO UP TO mt, nt = 8 ***

A RAMB18 in 32-bit mode holds 512 words. At kmax=64 the old depth of 64 used
12.5% of one primitive per bank. Depths up to 512 -- i.e. mt, nt up to 8 --
still infer exactly one RAMB18 per bank, so the 32x RAMB18 figure does not
move. Past 8 it doubles.

*** SIGNALS THAT MUST BE STABLE ACROSS A CALL ***

k_val, fold_i and fold_j are all sampled combinationally by the read path
while ap_start..ap_done is in flight. Drive all three from registers that
only change while the core is idle. Changing fold_i mid-call repoints every
A read at a different block of rows partway through the reduction, which
produces a plausible-looking wrong answer rather than an obvious failure.

*** THE ONE THING THAT WILL SILENTLY CORRUPT RESULTS *** (unchanged)

ap_memory has a one-cycle read latency: the core drives address0/ce0 on beat
t and expects q0 to be valid on beat t+1. The RAM below is written to match
(q registered off the clock). If you replace it with a combinational lookup,
q0 arrives a cycle early, every PE reads the wrong element of its row, and
the result is wrong in a way that csim cannot see -- csim never models the
memory interface at all. Only cosim or hardware will catch it.

Verify with cosim before building a bitstream.

*** REGRESSION CHECK -- RUN THIS FIRST ***

With mt = nt = 1 this generator emits the legacy wrapper verbatim: no fold
ports, depth kmax, the original write-address layout. Line 1 differs only in
the generator's own filename. So

    python3 gen_matmul_iface_fold_new.py 8 64 1 1 > /tmp/iface_mt1.v
    diff <(tail -n +2 rtl/matmul_iface_rk.v) <(tail -n +2 /tmp/iface_mt1.v)

must print nothing. That is a proof the change is an identity transform on
the path the known-good bitstream uses; without it, a later failure cannot be
attributed to either the fold logic or the refactor.
"""

import sys

BANNER = "gen_matmul_iface_fold_new.py"


def clog2(x):
    """Bits needed to index x entries. clog2(64)=6, clog2(8)=3."""
    return max(1, (x - 1).bit_length())


def foldw(x):
    """Bits needed to select among x folds. 1 fold -> no bits at all."""
    return 0 if x <= 1 else (x - 1).bit_length()


def generate(n, kmax, mt=1, nt=1):
    assert kmax & (kmax - 1) == 0, (
        f"kmax={kmax} is not a power of two; the {{fold, word}} concatenation "
        "in this generator would need to become a multiply-add")
    assert mt >= 1 and nt >= 1

    elems = n * n
    dw = elems * 32                 # flat width for C only
    word_w = clog2(kmax)            # 6 bits at K_MAX=64
    bank_w = clog2(n)               # 3 bits at 8 rows

    fi_w = foldw(mt)                # fold-select width for A
    fj_w = foldw(nt)                # fold-select width for B
    fold_w = max(fi_w, fj_w)        # width of the fold field in ab_waddr
    multifold = fold_w > 0

    waddr_w = bank_w + fold_w + word_w

    # Bit positions inside ab_waddr = {bank, fold, word}
    bank_hi, bank_lo = waddr_w - 1, word_w + fold_w
    a_depth = kmax * mt
    b_depth = kmax * nt

    L = []
    a = L.append

    a(f"// Auto-generated by {BANNER} ({n}x{n}, K_MAX={kmax}"
      + (f", MT={mt}, NT={nt}" if multifold else "") + ")")
    a("// -- 請勿手動修改")
    a("//")
    a("// Runtime-K interface wrapper. A and B live in RAM inside this module;")
    a("// the UART side fills them through one linear write port, and the core")
    a("// reads them through 2*N independent ap_memory ports.")
    a("//")
    a("// WRITE ADDRESS LAYOUT")
    a(f"//   ab_waddr[{bank_hi}:{bank_lo}] = bank  (row of A, or column of B)")
    if multifold:
        a(f"//   ab_waddr[{word_w+fold_w-1}:{word_w}] = fold  "
          f"(A uses the low {fi_w}, B the low {fj_w})")
    a(f"//   ab_waddr[{word_w-1}:0] = word  (position along K)")
    if multifold:
        a("// The host streams, for each fold, row 0 words 0..K-1, then row 1,")
        a("// and so on. Words at or beyond K are never read by the core -- it")
        a("// stops the time loop at K + R + C - 2 -- so they do not need")
        a("// clearing between calls.")
        a("//")
        a("// READ ADDRESSING")
        a(f"//   A bank i reads {{fold_i, address0}}, B bank j reads "
          f"{{fold_j, address0}}.")
        a("// K_MAX is a power of two, so this concatenation *is* the offset")
        a("// fold*K_MAX + word. No adder is inferred.")
    else:
        a("// The host streams row 0 words 0..K-1, then row 1, and so on. Words at")
        a("// or beyond K are never read by the core -- it stops the time loop at")
        a("// K + R + C - 2 -- so they do not need clearing between calls.")
    a("//")
    if multifold:
        a("// k_val, fold_i and fold_j MUST ALL BE STABLE while ap_start..ap_done")
        a("// is in flight: they are sampled combinationally rather than latched.")
        a("// Drive them from registers that only change while the core is idle.")
    else:
        a("// K MUST BE STABLE while ap_start..ap_done is in flight: it is bound as")
        a("// ap_none, meaning the core samples it combinationally rather than")
        a("// latching it. Drive it from a register that only changes while idle.")
    a("module matmul_iface_rk (")
    a("    input  wire        ap_clk,")
    a("    input  wire        ap_rst,")
    a("    input  wire        ap_start,")
    a("    output wire        ap_done,")
    a("    output wire        ap_idle,")
    a("    output wire        ap_ready,")
    a("")
    a("    // reduction length, held stable across a call")
    a("    input  wire [31:0] k_val,")
    a("")
    if multifold:
        a("    // fold selects, held stable across a call")
        if fi_w:
            a(f"    input  wire [{fi_w-1}:0]   fold_i,")
        if fj_w:
            a(f"    input  wire [{fj_w-1}:0]   fold_j,")
        a("")
    a("    // operand fill port (one word per clock)")
    a("    input  wire        a_we,")
    a("    input  wire        b_we,")
    a(f"    input  wire [{waddr_w-1}:0]  ab_waddr,")
    a("    input  wire [31:0] ab_wdata,")
    a("")
    a("    // C stays flat: R and C are still compile-time")
    a(f"    input  wire [{dw-1}:0] arg2_in_flat,")
    a(f"    output wire [{dw-1}:0] arg2_out_flat,")
    a(f"    output wire [{elems-1}:0]   arg2_vld_flat")
    a(");")
    a("")

    # ---- operand storage --------------------------------------------
    # One RAM per bank rather than one wide RAM with N read ports: the
    # core reads all N banks in the same cycle, so a shared memory would
    # need N ports and would not map to any real primitive.
    a("    // ---- operand RAMs ------------------------------------------")
    for tag, we, depth, sel_w, sel in (("a", "a_we", a_depth, fi_w, "fold_i"),
                                       ("b", "b_we", b_depth, fj_w, "fold_j")):
        for i in range(n):
            a(f"    reg [31:0] {tag}_mem_{i} [0:{depth-1}];")
            a(f"    reg [31:0] {tag}_q_{i};")
        a("")
        for i in range(n):
            a(f"    wire [{word_w-1}:0] {tag}_raddr_{i};")
        a("")

        # Write address into this bank's RAM, and read address from the core.
        if sel_w:
            waddr_expr = (f"{{ab_waddr[{word_w+sel_w-1}:{word_w}], "
                          f"ab_waddr[{word_w-1}:0]}}")
        else:
            waddr_expr = f"ab_waddr[{word_w-1}:0]"

        for i in range(n):
            raddr_expr = (f"{{{sel}, {tag}_raddr_{i}}}" if sel_w
                          else f"{tag}_raddr_{i}")
            a(f"    always @(posedge ap_clk) begin")
            a(f"        if ({we} && ab_waddr[{bank_hi}:{bank_lo}] == "
              f"{bank_w}'d{i})")
            a(f"            {tag}_mem_{i}[{waddr_expr}] <= ab_wdata;")
            # Read is unconditional rather than gated on ce0. Gating buys a
            # little power and costs a chance to get the enable timing wrong;
            # the core only samples q0 on cycles where it asserted ce0, so an
            # extra read is harmless.
            a(f"        {tag}_q_{i} <= {tag}_mem_{i}[{raddr_expr}];")
            a(f"    end")
        a("")

    # ---- C plumbing, unchanged in shape from the old generator -------
    a("    // ---- C: flat in, flat out ----------------------------------")
    for i in range(n):
        for j in range(n):
            idx = i * n + j
            hi, lo = idx * 32 + 31, idx * 32
            a(f"    wire [31:0] w_arg2_in_{i}_{j} = arg2_in_flat[{hi}:{lo}];")
    a("")
    a(f"    wire [31:0] w_arg2o   [0:{elems-1}];")
    a(f"    wire        w_arg2vld [0:{elems-1}];")
    a("")
    for i in range(n):
        for j in range(n):
            idx = i * n + j
            hi, lo = idx * 32 + 31, idx * 32
            a(f"    assign arg2_out_flat[{hi}:{lo}] = w_arg2o[{idx}];")
            a(f"    assign arg2_vld_flat[{idx}] = w_arg2vld[{idx}];")
    a("")

    # ---- the core ---------------------------------------------------
    a("    // ---- core --------------------------------------------------")
    a("    matmul_8x8x8 u_matmul (")
    a("        .ap_clk(ap_clk),")
    a("        .ap_rst(ap_rst),")
    a("        .ap_start(ap_start),")
    a("        .ap_done(ap_done),")
    a("        .ap_idle(ap_idle),")
    a("        .ap_ready(ap_ready),")
    a("        .K(k_val),")
    conns = []
    for tag, port in (("a", "A"), ("b", "B")):
        for i in range(n):
            # ce0 is left unconnected on purpose: the read above is
            # unconditional, so nothing consumes it. Vivado will warn about
            # an unused output; that warning is expected.
            conns.append(f"        .{port}_{i}_address0({tag}_raddr_{i})")
            conns.append(f"        .{port}_{i}_ce0()")
            conns.append(f"        .{port}_{i}_q0({tag}_q_{i})")
    for i in range(n):
        for j in range(n):
            idx = i * n + j
            conns.append(f"        .Cinout_{i}_{j}_i(w_arg2_in_{i}_{j})")
            conns.append(f"        .Cinout_{i}_{j}_o(w_arg2o[{idx}])")
            conns.append(f"        .Cinout_{i}_{j}_o_ap_vld(w_arg2vld[{idx}])")
    a(",\n".join(conns))
    a("    );")
    a("")
    a("endmodule")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 8
    kmax = int(sys.argv[2]) if len(sys.argv) > 2 else 64
    mt = int(sys.argv[3]) if len(sys.argv) > 3 else 1
    nt = int(sys.argv[4]) if len(sys.argv) > 4 else 1
    sys.stdout.write(generate(n, kmax, mt, nt))
