#!/usr/bin/env python3
"""Generate matmul_iface_rk.v -- the runtime-K interface wrapper.

    python3 gen_matmul_iface_new.py 8 64 > matmul_iface_rk.v

WHAT CHANGED FROM gen_matmul_iface.py, AND WHY

The fixed-K core took A and B as R*C individual 32-bit ports, so the old
generator could flatten them into one 2048-bit vector each and let the UART
controller shift bytes into a single register. The runtime-K core exports
them as ap_memory instead:

    output [5:0]  A_0_address0
    output        A_0_ce0
    input  [31:0] A_0_q0            (x8 for A, x8 for B)

Eight banks of K_MAX words. Flattening that would mean a 16384-bit port per
operand, which is not a sensible thing to build. So the storage moves inside
this wrapper: 16 small RAMs, one linear write port for the UART side, and
eight read ports wired straight to the core.

C is untouched. R and C are still compile-time, so Cinout stays flat.

MODULE NAME
Deliberately matmul_iface_rk, not matmul_iface. Two modules with the same
name in rtl/ would collide, and keeping the old one intact means the known-
good 40 MHz fixed-K build stays buildable while this is in progress.
matmul_top_dual.v has to be updated to instantiate the new name -- see the
port list printed in the header comment of the generated file.

*** THE ONE THING THAT WILL SILENTLY CORRUPT RESULTS ***

ap_memory has a one-cycle read latency: the core drives address0/ce0 on beat
t and expects q0 to be valid on beat t+1. The RAM below is written to match
(q registered off the clock). If you replace it with a combinational lookup,
q0 arrives a cycle early, every PE reads the wrong element of its row, and
the result is wrong in a way that csim cannot see -- csim never models the
memory interface at all. Only cosim or hardware will catch it.

Verify with cosim before building a bitstream.
"""

import sys


def clog2(x):
    """Bits needed to index x entries. clog2(64)=6, clog2(8)=3."""
    return max(1, (x - 1).bit_length())


def generate(n, kmax):
    elems = n * n
    dw = elems * 32                 # flat width for C only
    word_w = clog2(kmax)            # 6 bits at K_MAX=64
    bank_w = clog2(n)               # 3 bits at 8 rows
    waddr_w = bank_w + word_w       # 9 bits: {bank, word}

    L = []
    a = L.append

    a(f"// Auto-generated by gen_matmul_iface_new.py ({n}x{n}, K_MAX={kmax})")
    a("// -- 請勿手動修改")
    a("//")
    a("// Runtime-K interface wrapper. A and B live in RAM inside this module;")
    a("// the UART side fills them through one linear write port, and the core")
    a("// reads them through 2*N independent ap_memory ports.")
    a("//")
    a("// WRITE ADDRESS LAYOUT")
    a(f"//   ab_waddr[{waddr_w-1}:{word_w}] = bank  (row of A, or column of B)")
    a(f"//   ab_waddr[{word_w-1}:0] = word  (position along K)")
    a("// The host streams row 0 words 0..K-1, then row 1, and so on. Words at")
    a("// or beyond K are never read by the core -- it stops the time loop at")
    a("// K + R + C - 2 -- so they do not need clearing between calls.")
    a("//")
    a("// K MUST BE STABLE while ap_start..ap_done is in flight: it is bound as")
    a("// ap_none, meaning the core samples it combinationally rather than")
    a("// latching it. Drive it from a register that only changes while idle.")
    a("module matmul_iface_rk (")
    a("    input  wire        ap_clk,")
    a("    input  wire        ap_rst,")
    a("    input  wire        ap_start,")
    a("    output wire        ap_done,")
    a("    output wire        ap_idle,")
    a("    output wire        ap_ready,")
    a("")
    a("    // reduction length, held stable across a call")
    a("    input  wire [31:0] k_val,")
    a("")
    a("    // operand fill port (one word per clock)")
    a("    input  wire        a_we,")
    a("    input  wire        b_we,")
    a(f"    input  wire [{waddr_w-1}:0]  ab_waddr,")
    a("    input  wire [31:0] ab_wdata,")
    a("")
    a("    // C stays flat: R and C are still compile-time")
    a(f"    input  wire [{dw-1}:0] arg2_in_flat,")
    a(f"    output wire [{dw-1}:0] arg2_out_flat,")
    a(f"    output wire [{elems-1}:0]   arg2_vld_flat")
    a(");")
    a("")

    # ---- operand storage --------------------------------------------
    # One RAM per bank rather than one wide RAM with N read ports: the
    # core reads all N banks in the same cycle, so a shared memory would
    # need N ports and would not map to any real primitive.
    a("    // ---- operand RAMs ------------------------------------------")
    for tag, we in (("a", "a_we"), ("b", "b_we")):
        for i in range(n):
            a(f"    reg [31:0] {tag}_mem_{i} [0:{kmax-1}];")
            a(f"    reg [31:0] {tag}_q_{i};")
        a("")
        for i in range(n):
            a(f"    wire [{word_w-1}:0] {tag}_raddr_{i};")
        a("")
        for i in range(n):
            a(f"    always @(posedge ap_clk) begin")
            a(f"        if ({we} && ab_waddr[{waddr_w-1}:{word_w}] == "
              f"{bank_w}'d{i})")
            a(f"            {tag}_mem_{i}[ab_waddr[{word_w-1}:0]] <= ab_wdata;")
            # Read is unconditional rather than gated on ce0. Gating buys a
            # little power and costs a chance to get the enable timing wrong;
            # the core only samples q0 on cycles where it asserted ce0, so an
            # extra read is harmless.
            a(f"        {tag}_q_{i} <= {tag}_mem_{i}[{tag}_raddr_{i}];")
            a(f"    end")
        a("")

    # ---- C plumbing, unchanged in shape from the old generator -------
    a("    // ---- C: flat in, flat out ----------------------------------")
    for i in range(n):
        for j in range(n):
            idx = i * n + j
            hi, lo = idx * 32 + 31, idx * 32
            a(f"    wire [31:0] w_arg2_in_{i}_{j} = arg2_in_flat[{hi}:{lo}];")
    a("")
    a(f"    wire [31:0] w_arg2o   [0:{elems-1}];")
    a(f"    wire        w_arg2vld [0:{elems-1}];")
    a("")
    for i in range(n):
        for j in range(n):
            idx = i * n + j
            hi, lo = idx * 32 + 31, idx * 32
            a(f"    assign arg2_out_flat[{hi}:{lo}] = w_arg2o[{idx}];")
            a(f"    assign arg2_vld_flat[{idx}] = w_arg2vld[{idx}];")
    a("")

    # ---- the core ---------------------------------------------------
    a("    // ---- core --------------------------------------------------")
    a("    matmul_8x8x8 u_matmul (")
    a("        .ap_clk(ap_clk),")
    a("        .ap_rst(ap_rst),")
    a("        .ap_start(ap_start),")
    a("        .ap_done(ap_done),")
    a("        .ap_idle(ap_idle),")
    a("        .ap_ready(ap_ready),")
    a("        .K(k_val),")
    conns = []
    for tag, port in (("a", "A"), ("b", "B")):
        for i in range(n):
            # ce0 is left unconnected on purpose: the read above is
            # unconditional, so nothing consumes it. Vivado will warn about
            # an unused output; that warning is expected.
            conns.append(f"        .{port}_{i}_address0({tag}_raddr_{i})")
            conns.append(f"        .{port}_{i}_ce0()")
            conns.append(f"        .{port}_{i}_q0({tag}_q_{i})")
    for i in range(n):
        for j in range(n):
            idx = i * n + j
            conns.append(f"        .Cinout_{i}_{j}_i(w_arg2_in_{i}_{j})")
            conns.append(f"        .Cinout_{i}_{j}_o(w_arg2o[{idx}])")
            conns.append(f"        .Cinout_{i}_{j}_o_ap_vld(w_arg2vld[{idx}])")
    a(",\n".join(conns))
    a("    );")
    a("")
    a("endmodule")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 8
    kmax = int(sys.argv[2]) if len(sys.argv) > 2 else 64
    sys.stdout.write(generate(n, kmax))
