// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matmul_4x4x4_matmul_4x4x4,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=46.744000,HLS_SYN_LAT=12,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=8963,HLS_SYN_LUT=13750,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module matmul_4x4x4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        arg0_0_0,
        arg0_0_1,
        arg0_0_2,
        arg0_0_3,
        arg0_1_0,
        arg0_1_1,
        arg0_1_2,
        arg0_1_3,
        arg0_2_0,
        arg0_2_1,
        arg0_2_2,
        arg0_2_3,
        arg0_3_0,
        arg0_3_1,
        arg0_3_2,
        arg0_3_3,
        arg1_0_0,
        arg1_0_1,
        arg1_0_2,
        arg1_0_3,
        arg1_1_0,
        arg1_1_1,
        arg1_1_2,
        arg1_1_3,
        arg1_2_0,
        arg1_2_1,
        arg1_2_2,
        arg1_2_3,
        arg1_3_0,
        arg1_3_1,
        arg1_3_2,
        arg1_3_3,
        arg2_0_0_i,
        arg2_0_0_o,
        arg2_0_0_o_ap_vld,
        arg2_0_1_i,
        arg2_0_1_o,
        arg2_0_1_o_ap_vld,
        arg2_0_2_i,
        arg2_0_2_o,
        arg2_0_2_o_ap_vld,
        arg2_0_3_i,
        arg2_0_3_o,
        arg2_0_3_o_ap_vld,
        arg2_1_0_i,
        arg2_1_0_o,
        arg2_1_0_o_ap_vld,
        arg2_1_1_i,
        arg2_1_1_o,
        arg2_1_1_o_ap_vld,
        arg2_1_2_i,
        arg2_1_2_o,
        arg2_1_2_o_ap_vld,
        arg2_1_3_i,
        arg2_1_3_o,
        arg2_1_3_o_ap_vld,
        arg2_2_0_i,
        arg2_2_0_o,
        arg2_2_0_o_ap_vld,
        arg2_2_1_i,
        arg2_2_1_o,
        arg2_2_1_o_ap_vld,
        arg2_2_2_i,
        arg2_2_2_o,
        arg2_2_2_o_ap_vld,
        arg2_2_3_i,
        arg2_2_3_o,
        arg2_2_3_o_ap_vld,
        arg2_3_0_i,
        arg2_3_0_o,
        arg2_3_0_o_ap_vld,
        arg2_3_1_i,
        arg2_3_1_o,
        arg2_3_1_o_ap_vld,
        arg2_3_2_i,
        arg2_3_2_o,
        arg2_3_2_o_ap_vld,
        arg2_3_3_i,
        arg2_3_3_o,
        arg2_3_3_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] arg0_0_0;
input  [31:0] arg0_0_1;
input  [31:0] arg0_0_2;
input  [31:0] arg0_0_3;
input  [31:0] arg0_1_0;
input  [31:0] arg0_1_1;
input  [31:0] arg0_1_2;
input  [31:0] arg0_1_3;
input  [31:0] arg0_2_0;
input  [31:0] arg0_2_1;
input  [31:0] arg0_2_2;
input  [31:0] arg0_2_3;
input  [31:0] arg0_3_0;
input  [31:0] arg0_3_1;
input  [31:0] arg0_3_2;
input  [31:0] arg0_3_3;
input  [31:0] arg1_0_0;
input  [31:0] arg1_0_1;
input  [31:0] arg1_0_2;
input  [31:0] arg1_0_3;
input  [31:0] arg1_1_0;
input  [31:0] arg1_1_1;
input  [31:0] arg1_1_2;
input  [31:0] arg1_1_3;
input  [31:0] arg1_2_0;
input  [31:0] arg1_2_1;
input  [31:0] arg1_2_2;
input  [31:0] arg1_2_3;
input  [31:0] arg1_3_0;
input  [31:0] arg1_3_1;
input  [31:0] arg1_3_2;
input  [31:0] arg1_3_3;
input  [31:0] arg2_0_0_i;
output  [31:0] arg2_0_0_o;
output   arg2_0_0_o_ap_vld;
input  [31:0] arg2_0_1_i;
output  [31:0] arg2_0_1_o;
output   arg2_0_1_o_ap_vld;
input  [31:0] arg2_0_2_i;
output  [31:0] arg2_0_2_o;
output   arg2_0_2_o_ap_vld;
input  [31:0] arg2_0_3_i;
output  [31:0] arg2_0_3_o;
output   arg2_0_3_o_ap_vld;
input  [31:0] arg2_1_0_i;
output  [31:0] arg2_1_0_o;
output   arg2_1_0_o_ap_vld;
input  [31:0] arg2_1_1_i;
output  [31:0] arg2_1_1_o;
output   arg2_1_1_o_ap_vld;
input  [31:0] arg2_1_2_i;
output  [31:0] arg2_1_2_o;
output   arg2_1_2_o_ap_vld;
input  [31:0] arg2_1_3_i;
output  [31:0] arg2_1_3_o;
output   arg2_1_3_o_ap_vld;
input  [31:0] arg2_2_0_i;
output  [31:0] arg2_2_0_o;
output   arg2_2_0_o_ap_vld;
input  [31:0] arg2_2_1_i;
output  [31:0] arg2_2_1_o;
output   arg2_2_1_o_ap_vld;
input  [31:0] arg2_2_2_i;
output  [31:0] arg2_2_2_o;
output   arg2_2_2_o_ap_vld;
input  [31:0] arg2_2_3_i;
output  [31:0] arg2_2_3_o;
output   arg2_2_3_o_ap_vld;
input  [31:0] arg2_3_0_i;
output  [31:0] arg2_3_0_o;
output   arg2_3_0_o_ap_vld;
input  [31:0] arg2_3_1_i;
output  [31:0] arg2_3_1_o;
output   arg2_3_1_o_ap_vld;
input  [31:0] arg2_3_2_i;
output  [31:0] arg2_3_2_o;
output   arg2_3_2_o_ap_vld;
input  [31:0] arg2_3_3_i;
output  [31:0] arg2_3_3_o;
output   arg2_3_3_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg arg2_0_0_o_ap_vld;
reg arg2_0_1_o_ap_vld;
reg arg2_0_2_o_ap_vld;
reg arg2_0_3_o_ap_vld;
reg arg2_1_0_o_ap_vld;
reg arg2_1_1_o_ap_vld;
reg arg2_1_2_o_ap_vld;
reg arg2_1_3_o_ap_vld;
reg arg2_2_0_o_ap_vld;
reg arg2_2_1_o_ap_vld;
reg arg2_2_2_o_ap_vld;
reg arg2_2_3_o_ap_vld;
reg arg2_3_0_o_ap_vld;
reg arg2_3_1_o_ap_vld;
reg arg2_3_2_o_ap_vld;
reg arg2_3_3_o_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] acc_fu_838_p1;
reg   [31:0] acc_reg_1398;
wire   [31:0] bitcast_ln12_fu_843_p1;
reg   [31:0] bitcast_ln12_reg_1403;
wire   [31:0] bitcast_ln12_1_fu_851_p1;
reg   [31:0] bitcast_ln12_1_reg_1411;
wire   [31:0] bitcast_ln12_2_fu_859_p1;
reg   [31:0] bitcast_ln12_2_reg_1419;
wire   [31:0] bitcast_ln12_3_fu_867_p1;
reg   [31:0] bitcast_ln12_3_reg_1427;
wire   [31:0] bitcast_ln12_4_fu_875_p1;
reg   [31:0] bitcast_ln12_4_reg_1435;
wire   [31:0] bitcast_ln12_5_fu_883_p1;
reg   [31:0] bitcast_ln12_5_reg_1443;
wire   [31:0] bitcast_ln12_6_fu_891_p1;
reg   [31:0] bitcast_ln12_6_reg_1451;
wire   [31:0] bitcast_ln12_7_fu_899_p1;
reg   [31:0] bitcast_ln12_7_reg_1459;
wire   [31:0] acc_15_fu_907_p1;
reg   [31:0] acc_15_reg_1467;
wire   [31:0] bitcast_ln12_8_fu_912_p1;
reg   [31:0] bitcast_ln12_8_reg_1472;
wire   [31:0] bitcast_ln12_9_fu_920_p1;
reg   [31:0] bitcast_ln12_9_reg_1480;
wire   [31:0] bitcast_ln12_10_fu_928_p1;
reg   [31:0] bitcast_ln12_10_reg_1488;
wire   [31:0] bitcast_ln12_11_fu_936_p1;
reg   [31:0] bitcast_ln12_11_reg_1496;
wire   [31:0] acc_17_fu_944_p1;
reg   [31:0] acc_17_reg_1504;
wire   [31:0] bitcast_ln12_12_fu_949_p1;
reg   [31:0] bitcast_ln12_12_reg_1509;
wire   [31:0] bitcast_ln12_13_fu_957_p1;
reg   [31:0] bitcast_ln12_13_reg_1517;
wire   [31:0] bitcast_ln12_14_fu_965_p1;
reg   [31:0] bitcast_ln12_14_reg_1525;
wire   [31:0] bitcast_ln12_15_fu_973_p1;
reg   [31:0] bitcast_ln12_15_reg_1533;
wire   [31:0] acc_18_fu_981_p1;
reg   [31:0] acc_18_reg_1541;
wire   [31:0] bitcast_ln12_16_fu_986_p1;
reg   [31:0] bitcast_ln12_16_reg_1546;
wire   [31:0] bitcast_ln12_17_fu_994_p1;
reg   [31:0] bitcast_ln12_17_reg_1554;
wire   [31:0] bitcast_ln12_18_fu_1002_p1;
reg   [31:0] bitcast_ln12_18_reg_1562;
wire   [31:0] bitcast_ln12_19_fu_1010_p1;
reg   [31:0] bitcast_ln12_19_reg_1570;
wire   [31:0] acc_20_fu_1018_p1;
reg   [31:0] acc_20_reg_1578;
wire   [31:0] bitcast_ln12_20_fu_1023_p1;
reg   [31:0] bitcast_ln12_20_reg_1583;
wire   [31:0] bitcast_ln12_21_fu_1031_p1;
reg   [31:0] bitcast_ln12_21_reg_1591;
wire   [31:0] bitcast_ln12_22_fu_1039_p1;
reg   [31:0] bitcast_ln12_22_reg_1599;
wire   [31:0] bitcast_ln12_23_fu_1047_p1;
reg   [31:0] bitcast_ln12_23_reg_1607;
wire   [31:0] acc_21_fu_1055_p1;
reg   [31:0] acc_21_reg_1615;
wire   [31:0] acc_23_fu_1060_p1;
reg   [31:0] acc_23_reg_1620;
wire   [31:0] acc_24_fu_1065_p1;
reg   [31:0] acc_24_reg_1625;
wire   [31:0] acc_26_fu_1070_p1;
reg   [31:0] acc_26_reg_1630;
wire   [31:0] bitcast_ln12_24_fu_1075_p1;
reg   [31:0] bitcast_ln12_24_reg_1635;
wire   [31:0] bitcast_ln12_25_fu_1083_p1;
reg   [31:0] bitcast_ln12_25_reg_1643;
wire   [31:0] bitcast_ln12_26_fu_1091_p1;
reg   [31:0] bitcast_ln12_26_reg_1651;
wire   [31:0] bitcast_ln12_27_fu_1099_p1;
reg   [31:0] bitcast_ln12_27_reg_1659;
wire   [31:0] acc_27_fu_1107_p1;
reg   [31:0] acc_27_reg_1667;
wire   [31:0] acc_28_fu_1112_p1;
reg   [31:0] acc_28_reg_1672;
wire   [31:0] acc_29_fu_1117_p1;
reg   [31:0] acc_29_reg_1677;
wire   [31:0] acc_30_fu_1122_p1;
reg   [31:0] acc_30_reg_1682;
wire   [31:0] bitcast_ln12_28_fu_1127_p1;
reg   [31:0] bitcast_ln12_28_reg_1687;
wire   [31:0] bitcast_ln12_29_fu_1135_p1;
reg   [31:0] bitcast_ln12_29_reg_1695;
wire   [31:0] bitcast_ln12_30_fu_1143_p1;
reg   [31:0] bitcast_ln12_30_reg_1703;
wire   [31:0] bitcast_ln12_31_fu_1151_p1;
reg   [31:0] bitcast_ln12_31_reg_1711;
wire   [31:0] acc_31_fu_1159_p1;
reg   [31:0] acc_31_reg_1719;
wire   [31:0] acc_32_fu_1164_p1;
reg   [31:0] acc_32_reg_1724;
wire   [31:0] acc_33_fu_1169_p1;
reg   [31:0] acc_33_reg_1729;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out_ap_vld;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_done;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_idle;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_ready;
wire   [31:0] grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out;
wire    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out_ap_vld;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg;
reg    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg = 1'b0;
#0 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg = 1'b0;
end

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_ready),
    .acc(acc_reg_1398),
    .bitcast_ln12(bitcast_ln12_reg_1403),
    .bitcast_ln12_1(bitcast_ln12_1_reg_1411),
    .bitcast_ln12_2(bitcast_ln12_2_reg_1419),
    .bitcast_ln12_3(bitcast_ln12_3_reg_1427),
    .bitcast_ln12_4(bitcast_ln12_4_reg_1435),
    .bitcast_ln12_5(bitcast_ln12_5_reg_1443),
    .bitcast_ln12_6(bitcast_ln12_6_reg_1451),
    .bitcast_ln12_7(bitcast_ln12_7_reg_1459),
    .acc_2_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out),
    .acc_2_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_ready),
    .acc_1(acc_15_reg_1467),
    .bitcast_ln12(bitcast_ln12_reg_1403),
    .bitcast_ln12_1(bitcast_ln12_1_reg_1411),
    .bitcast_ln12_2(bitcast_ln12_2_reg_1419),
    .bitcast_ln12_3(bitcast_ln12_3_reg_1427),
    .bitcast_ln12_8(bitcast_ln12_8_reg_1472),
    .bitcast_ln12_9(bitcast_ln12_9_reg_1480),
    .bitcast_ln12_10(bitcast_ln12_10_reg_1488),
    .bitcast_ln12_11(bitcast_ln12_11_reg_1496),
    .acc_5_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out),
    .acc_5_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_ready),
    .acc_4(acc_17_reg_1504),
    .bitcast_ln12(bitcast_ln12_reg_1403),
    .bitcast_ln12_1(bitcast_ln12_1_reg_1411),
    .bitcast_ln12_2(bitcast_ln12_2_reg_1419),
    .bitcast_ln12_3(bitcast_ln12_3_reg_1427),
    .bitcast_ln12_12(bitcast_ln12_12_reg_1509),
    .bitcast_ln12_13(bitcast_ln12_13_reg_1517),
    .bitcast_ln12_14(bitcast_ln12_14_reg_1525),
    .bitcast_ln12_15(bitcast_ln12_15_reg_1533),
    .acc_8_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out),
    .acc_8_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_ready),
    .acc_7(acc_18_reg_1541),
    .bitcast_ln12(bitcast_ln12_reg_1403),
    .bitcast_ln12_1(bitcast_ln12_1_reg_1411),
    .bitcast_ln12_2(bitcast_ln12_2_reg_1419),
    .bitcast_ln12_3(bitcast_ln12_3_reg_1427),
    .bitcast_ln12_16(bitcast_ln12_16_reg_1546),
    .bitcast_ln12_17(bitcast_ln12_17_reg_1554),
    .bitcast_ln12_18(bitcast_ln12_18_reg_1562),
    .bitcast_ln12_19(bitcast_ln12_19_reg_1570),
    .acc_11_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out),
    .acc_11_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_ready),
    .acc_10(acc_20_reg_1578),
    .bitcast_ln12_20(bitcast_ln12_20_reg_1583),
    .bitcast_ln12_21(bitcast_ln12_21_reg_1591),
    .bitcast_ln12_22(bitcast_ln12_22_reg_1599),
    .bitcast_ln12_23(bitcast_ln12_23_reg_1607),
    .bitcast_ln12_4(bitcast_ln12_4_reg_1435),
    .bitcast_ln12_5(bitcast_ln12_5_reg_1443),
    .bitcast_ln12_6(bitcast_ln12_6_reg_1451),
    .bitcast_ln12_7(bitcast_ln12_7_reg_1459),
    .acc_14_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out),
    .acc_14_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_ready),
    .acc_13(acc_21_reg_1615),
    .bitcast_ln12_20(bitcast_ln12_20_reg_1583),
    .bitcast_ln12_21(bitcast_ln12_21_reg_1591),
    .bitcast_ln12_22(bitcast_ln12_22_reg_1599),
    .bitcast_ln12_23(bitcast_ln12_23_reg_1607),
    .bitcast_ln12_8(bitcast_ln12_8_reg_1472),
    .bitcast_ln12_9(bitcast_ln12_9_reg_1480),
    .bitcast_ln12_10(bitcast_ln12_10_reg_1488),
    .bitcast_ln12_11(bitcast_ln12_11_reg_1496),
    .acc_17_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out),
    .acc_17_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_ready),
    .acc_16(acc_23_reg_1620),
    .bitcast_ln12_20(bitcast_ln12_20_reg_1583),
    .bitcast_ln12_21(bitcast_ln12_21_reg_1591),
    .bitcast_ln12_22(bitcast_ln12_22_reg_1599),
    .bitcast_ln12_23(bitcast_ln12_23_reg_1607),
    .bitcast_ln12_12(bitcast_ln12_12_reg_1509),
    .bitcast_ln12_13(bitcast_ln12_13_reg_1517),
    .bitcast_ln12_14(bitcast_ln12_14_reg_1525),
    .bitcast_ln12_15(bitcast_ln12_15_reg_1533),
    .acc_20_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out),
    .acc_20_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_ready),
    .acc_19(acc_24_reg_1625),
    .bitcast_ln12_20(bitcast_ln12_20_reg_1583),
    .bitcast_ln12_21(bitcast_ln12_21_reg_1591),
    .bitcast_ln12_22(bitcast_ln12_22_reg_1599),
    .bitcast_ln12_23(bitcast_ln12_23_reg_1607),
    .bitcast_ln12_16(bitcast_ln12_16_reg_1546),
    .bitcast_ln12_17(bitcast_ln12_17_reg_1554),
    .bitcast_ln12_18(bitcast_ln12_18_reg_1562),
    .bitcast_ln12_19(bitcast_ln12_19_reg_1570),
    .acc_23_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out),
    .acc_23_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_ready),
    .acc_22(acc_26_reg_1630),
    .bitcast_ln12_24(bitcast_ln12_24_reg_1635),
    .bitcast_ln12_25(bitcast_ln12_25_reg_1643),
    .bitcast_ln12_26(bitcast_ln12_26_reg_1651),
    .bitcast_ln12_27(bitcast_ln12_27_reg_1659),
    .bitcast_ln12_4(bitcast_ln12_4_reg_1435),
    .bitcast_ln12_5(bitcast_ln12_5_reg_1443),
    .bitcast_ln12_6(bitcast_ln12_6_reg_1451),
    .bitcast_ln12_7(bitcast_ln12_7_reg_1459),
    .acc_26_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out),
    .acc_26_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_ready),
    .acc_25(acc_27_reg_1667),
    .bitcast_ln12_24(bitcast_ln12_24_reg_1635),
    .bitcast_ln12_25(bitcast_ln12_25_reg_1643),
    .bitcast_ln12_26(bitcast_ln12_26_reg_1651),
    .bitcast_ln12_27(bitcast_ln12_27_reg_1659),
    .bitcast_ln12_8(bitcast_ln12_8_reg_1472),
    .bitcast_ln12_9(bitcast_ln12_9_reg_1480),
    .bitcast_ln12_10(bitcast_ln12_10_reg_1488),
    .bitcast_ln12_11(bitcast_ln12_11_reg_1496),
    .acc_29_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out),
    .acc_29_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_ready),
    .acc_28(acc_28_reg_1672),
    .bitcast_ln12_24(bitcast_ln12_24_reg_1635),
    .bitcast_ln12_25(bitcast_ln12_25_reg_1643),
    .bitcast_ln12_26(bitcast_ln12_26_reg_1651),
    .bitcast_ln12_27(bitcast_ln12_27_reg_1659),
    .bitcast_ln12_12(bitcast_ln12_12_reg_1509),
    .bitcast_ln12_13(bitcast_ln12_13_reg_1517),
    .bitcast_ln12_14(bitcast_ln12_14_reg_1525),
    .bitcast_ln12_15(bitcast_ln12_15_reg_1533),
    .acc_32_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out),
    .acc_32_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_ready),
    .acc_31(acc_29_reg_1677),
    .bitcast_ln12_24(bitcast_ln12_24_reg_1635),
    .bitcast_ln12_25(bitcast_ln12_25_reg_1643),
    .bitcast_ln12_26(bitcast_ln12_26_reg_1651),
    .bitcast_ln12_27(bitcast_ln12_27_reg_1659),
    .bitcast_ln12_16(bitcast_ln12_16_reg_1546),
    .bitcast_ln12_17(bitcast_ln12_17_reg_1554),
    .bitcast_ln12_18(bitcast_ln12_18_reg_1562),
    .bitcast_ln12_19(bitcast_ln12_19_reg_1570),
    .acc_35_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out),
    .acc_35_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_ready),
    .acc_34(acc_30_reg_1682),
    .bitcast_ln12_28(bitcast_ln12_28_reg_1687),
    .bitcast_ln12_29(bitcast_ln12_29_reg_1695),
    .bitcast_ln12_30(bitcast_ln12_30_reg_1703),
    .bitcast_ln12_31(bitcast_ln12_31_reg_1711),
    .bitcast_ln12_4(bitcast_ln12_4_reg_1435),
    .bitcast_ln12_5(bitcast_ln12_5_reg_1443),
    .bitcast_ln12_6(bitcast_ln12_6_reg_1451),
    .bitcast_ln12_7(bitcast_ln12_7_reg_1459),
    .acc_38_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out),
    .acc_38_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_ready),
    .acc_37(acc_31_reg_1719),
    .bitcast_ln12_28(bitcast_ln12_28_reg_1687),
    .bitcast_ln12_29(bitcast_ln12_29_reg_1695),
    .bitcast_ln12_30(bitcast_ln12_30_reg_1703),
    .bitcast_ln12_31(bitcast_ln12_31_reg_1711),
    .bitcast_ln12_8(bitcast_ln12_8_reg_1472),
    .bitcast_ln12_9(bitcast_ln12_9_reg_1480),
    .bitcast_ln12_10(bitcast_ln12_10_reg_1488),
    .bitcast_ln12_11(bitcast_ln12_11_reg_1496),
    .acc_41_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out),
    .acc_41_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_ready),
    .acc_40(acc_32_reg_1724),
    .bitcast_ln12_28(bitcast_ln12_28_reg_1687),
    .bitcast_ln12_29(bitcast_ln12_29_reg_1695),
    .bitcast_ln12_30(bitcast_ln12_30_reg_1703),
    .bitcast_ln12_31(bitcast_ln12_31_reg_1711),
    .bitcast_ln12_12(bitcast_ln12_12_reg_1509),
    .bitcast_ln12_13(bitcast_ln12_13_reg_1517),
    .bitcast_ln12_14(bitcast_ln12_14_reg_1525),
    .bitcast_ln12_15(bitcast_ln12_15_reg_1533),
    .acc_44_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out),
    .acc_44_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out_ap_vld)
);

matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315 grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start),
    .ap_done(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_done),
    .ap_idle(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_idle),
    .ap_ready(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_ready),
    .acc_43(acc_33_reg_1729),
    .bitcast_ln12_28(bitcast_ln12_28_reg_1687),
    .bitcast_ln12_29(bitcast_ln12_29_reg_1695),
    .bitcast_ln12_30(bitcast_ln12_30_reg_1703),
    .bitcast_ln12_31(bitcast_ln12_31_reg_1711),
    .bitcast_ln12_16(bitcast_ln12_16_reg_1546),
    .bitcast_ln12_17(bitcast_ln12_17_reg_1554),
    .bitcast_ln12_18(bitcast_ln12_18_reg_1562),
    .bitcast_ln12_19(bitcast_ln12_19_reg_1570),
    .acc_46_out(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out),
    .acc_46_out_ap_vld(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_ready == 1'b1)) begin
            grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        acc_15_reg_1467 <= acc_15_fu_907_p1;
        acc_17_reg_1504 <= acc_17_fu_944_p1;
        acc_18_reg_1541 <= acc_18_fu_981_p1;
        acc_20_reg_1578 <= acc_20_fu_1018_p1;
        acc_21_reg_1615 <= acc_21_fu_1055_p1;
        acc_23_reg_1620 <= acc_23_fu_1060_p1;
        acc_24_reg_1625 <= acc_24_fu_1065_p1;
        acc_26_reg_1630 <= acc_26_fu_1070_p1;
        acc_27_reg_1667 <= acc_27_fu_1107_p1;
        acc_28_reg_1672 <= acc_28_fu_1112_p1;
        acc_29_reg_1677 <= acc_29_fu_1117_p1;
        acc_30_reg_1682 <= acc_30_fu_1122_p1;
        acc_31_reg_1719 <= acc_31_fu_1159_p1;
        acc_32_reg_1724 <= acc_32_fu_1164_p1;
        acc_33_reg_1729 <= acc_33_fu_1169_p1;
        acc_reg_1398 <= acc_fu_838_p1;
        bitcast_ln12_10_reg_1488 <= bitcast_ln12_10_fu_928_p1;
        bitcast_ln12_11_reg_1496 <= bitcast_ln12_11_fu_936_p1;
        bitcast_ln12_12_reg_1509 <= bitcast_ln12_12_fu_949_p1;
        bitcast_ln12_13_reg_1517 <= bitcast_ln12_13_fu_957_p1;
        bitcast_ln12_14_reg_1525 <= bitcast_ln12_14_fu_965_p1;
        bitcast_ln12_15_reg_1533 <= bitcast_ln12_15_fu_973_p1;
        bitcast_ln12_16_reg_1546 <= bitcast_ln12_16_fu_986_p1;
        bitcast_ln12_17_reg_1554 <= bitcast_ln12_17_fu_994_p1;
        bitcast_ln12_18_reg_1562 <= bitcast_ln12_18_fu_1002_p1;
        bitcast_ln12_19_reg_1570 <= bitcast_ln12_19_fu_1010_p1;
        bitcast_ln12_1_reg_1411 <= bitcast_ln12_1_fu_851_p1;
        bitcast_ln12_20_reg_1583 <= bitcast_ln12_20_fu_1023_p1;
        bitcast_ln12_21_reg_1591 <= bitcast_ln12_21_fu_1031_p1;
        bitcast_ln12_22_reg_1599 <= bitcast_ln12_22_fu_1039_p1;
        bitcast_ln12_23_reg_1607 <= bitcast_ln12_23_fu_1047_p1;
        bitcast_ln12_24_reg_1635 <= bitcast_ln12_24_fu_1075_p1;
        bitcast_ln12_25_reg_1643 <= bitcast_ln12_25_fu_1083_p1;
        bitcast_ln12_26_reg_1651 <= bitcast_ln12_26_fu_1091_p1;
        bitcast_ln12_27_reg_1659 <= bitcast_ln12_27_fu_1099_p1;
        bitcast_ln12_28_reg_1687 <= bitcast_ln12_28_fu_1127_p1;
        bitcast_ln12_29_reg_1695 <= bitcast_ln12_29_fu_1135_p1;
        bitcast_ln12_2_reg_1419 <= bitcast_ln12_2_fu_859_p1;
        bitcast_ln12_30_reg_1703 <= bitcast_ln12_30_fu_1143_p1;
        bitcast_ln12_31_reg_1711 <= bitcast_ln12_31_fu_1151_p1;
        bitcast_ln12_3_reg_1427 <= bitcast_ln12_3_fu_867_p1;
        bitcast_ln12_4_reg_1435 <= bitcast_ln12_4_fu_875_p1;
        bitcast_ln12_5_reg_1443 <= bitcast_ln12_5_fu_883_p1;
        bitcast_ln12_6_reg_1451 <= bitcast_ln12_6_fu_891_p1;
        bitcast_ln12_7_reg_1459 <= bitcast_ln12_7_fu_899_p1;
        bitcast_ln12_8_reg_1472 <= bitcast_ln12_8_fu_912_p1;
        bitcast_ln12_9_reg_1480 <= bitcast_ln12_9_fu_920_p1;
        bitcast_ln12_reg_1403 <= bitcast_ln12_fu_843_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_0_0_o_ap_vld = 1'b1;
    end else begin
        arg2_0_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_0_1_o_ap_vld = 1'b1;
    end else begin
        arg2_0_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_0_2_o_ap_vld = 1'b1;
    end else begin
        arg2_0_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_0_3_o_ap_vld = 1'b1;
    end else begin
        arg2_0_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_1_0_o_ap_vld = 1'b1;
    end else begin
        arg2_1_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_1_1_o_ap_vld = 1'b1;
    end else begin
        arg2_1_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_1_2_o_ap_vld = 1'b1;
    end else begin
        arg2_1_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_1_3_o_ap_vld = 1'b1;
    end else begin
        arg2_1_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_2_0_o_ap_vld = 1'b1;
    end else begin
        arg2_2_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_2_1_o_ap_vld = 1'b1;
    end else begin
        arg2_2_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_2_2_o_ap_vld = 1'b1;
    end else begin
        arg2_2_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_2_3_o_ap_vld = 1'b1;
    end else begin
        arg2_2_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_3_0_o_ap_vld = 1'b1;
    end else begin
        arg2_3_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_3_1_o_ap_vld = 1'b1;
    end else begin
        arg2_3_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_3_2_o_ap_vld = 1'b1;
    end else begin
        arg2_3_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arg2_3_3_o_ap_vld = 1'b1;
    end else begin
        arg2_3_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_15_fu_907_p1 = arg2_0_1_i;

assign acc_17_fu_944_p1 = arg2_0_2_i;

assign acc_18_fu_981_p1 = arg2_0_3_i;

assign acc_20_fu_1018_p1 = arg2_1_0_i;

assign acc_21_fu_1055_p1 = arg2_1_1_i;

assign acc_23_fu_1060_p1 = arg2_1_2_i;

assign acc_24_fu_1065_p1 = arg2_1_3_i;

assign acc_26_fu_1070_p1 = arg2_2_0_i;

assign acc_27_fu_1107_p1 = arg2_2_1_i;

assign acc_28_fu_1112_p1 = arg2_2_2_i;

assign acc_29_fu_1117_p1 = arg2_2_3_i;

assign acc_30_fu_1122_p1 = arg2_3_0_i;

assign acc_31_fu_1159_p1 = arg2_3_1_i;

assign acc_32_fu_1164_p1 = arg2_3_2_i;

assign acc_33_fu_1169_p1 = arg2_3_3_i;

assign acc_fu_838_p1 = arg2_0_0_i;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_done == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_done 
    == 1'b0) | (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_done == 1'b0));
end

assign arg2_0_0_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out;

assign arg2_0_1_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out;

assign arg2_0_2_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out;

assign arg2_0_3_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out;

assign arg2_1_0_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out;

assign arg2_1_1_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out;

assign arg2_1_2_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out;

assign arg2_1_3_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out;

assign arg2_2_0_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out;

assign arg2_2_1_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out;

assign arg2_2_2_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out;

assign arg2_2_3_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out;

assign arg2_3_0_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out;

assign arg2_3_1_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out;

assign arg2_3_2_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out;

assign arg2_3_3_o = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out;

assign bitcast_ln12_10_fu_928_p1 = arg1_2_1;

assign bitcast_ln12_11_fu_936_p1 = arg1_3_1;

assign bitcast_ln12_12_fu_949_p1 = arg1_0_2;

assign bitcast_ln12_13_fu_957_p1 = arg1_1_2;

assign bitcast_ln12_14_fu_965_p1 = arg1_2_2;

assign bitcast_ln12_15_fu_973_p1 = arg1_3_2;

assign bitcast_ln12_16_fu_986_p1 = arg1_0_3;

assign bitcast_ln12_17_fu_994_p1 = arg1_1_3;

assign bitcast_ln12_18_fu_1002_p1 = arg1_2_3;

assign bitcast_ln12_19_fu_1010_p1 = arg1_3_3;

assign bitcast_ln12_1_fu_851_p1 = arg0_0_1;

assign bitcast_ln12_20_fu_1023_p1 = arg0_1_0;

assign bitcast_ln12_21_fu_1031_p1 = arg0_1_1;

assign bitcast_ln12_22_fu_1039_p1 = arg0_1_2;

assign bitcast_ln12_23_fu_1047_p1 = arg0_1_3;

assign bitcast_ln12_24_fu_1075_p1 = arg0_2_0;

assign bitcast_ln12_25_fu_1083_p1 = arg0_2_1;

assign bitcast_ln12_26_fu_1091_p1 = arg0_2_2;

assign bitcast_ln12_27_fu_1099_p1 = arg0_2_3;

assign bitcast_ln12_28_fu_1127_p1 = arg0_3_0;

assign bitcast_ln12_29_fu_1135_p1 = arg0_3_1;

assign bitcast_ln12_2_fu_859_p1 = arg0_0_2;

assign bitcast_ln12_30_fu_1143_p1 = arg0_3_2;

assign bitcast_ln12_31_fu_1151_p1 = arg0_3_3;

assign bitcast_ln12_3_fu_867_p1 = arg0_0_3;

assign bitcast_ln12_4_fu_875_p1 = arg1_0_0;

assign bitcast_ln12_5_fu_883_p1 = arg1_1_0;

assign bitcast_ln12_6_fu_891_p1 = arg1_2_0;

assign bitcast_ln12_7_fu_899_p1 = arg1_3_0;

assign bitcast_ln12_8_fu_912_p1 = arg1_0_1;

assign bitcast_ln12_9_fu_920_p1 = arg1_1_1;

assign bitcast_ln12_fu_843_p1 = arg0_0_0;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg;

assign grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start = grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg;

endmodule //matmul_4x4x4
