// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acc_13,
        bitcast_ln12_20,
        bitcast_ln12_21,
        bitcast_ln12_22,
        bitcast_ln12_23,
        bitcast_ln12_8,
        bitcast_ln12_9,
        bitcast_ln12_10,
        bitcast_ln12_11,
        acc_17_out,
        acc_17_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] acc_13;
input  [31:0] bitcast_ln12_20;
input  [31:0] bitcast_ln12_21;
input  [31:0] bitcast_ln12_22;
input  [31:0] bitcast_ln12_23;
input  [31:0] bitcast_ln12_8;
input  [31:0] bitcast_ln12_9;
input  [31:0] bitcast_ln12_10;
input  [31:0] bitcast_ln12_11;
output  [31:0] acc_17_out;
output   acc_17_out_ap_vld;

reg ap_idle;
reg acc_17_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln10_fu_150_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln10_reg_249;
reg   [0:0] icmp_ln10_reg_249_pp0_iter1_reg;
reg   [0:0] icmp_ln10_reg_249_pp0_iter2_reg;
reg   [0:0] icmp_ln10_reg_249_pp0_iter3_reg;
wire   [31:0] tmp_s_fu_166_p11;
wire   [31:0] tmp_5_fu_191_p11;
wire   [31:0] grp_fu_133_p2;
reg   [31:0] mul_1_1_reg_263;
reg   [31:0] acc_fu_60;
wire   [31:0] grp_fu_129_p2;
reg   [31:0] ap_sig_allocacmp_acc_load_5;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [2:0] k_fu_64;
wire   [2:0] add_ln10_fu_156_p2;
reg   [2:0] ap_sig_allocacmp_k_5;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] tmp_s_fu_166_p9;
wire   [1:0] trunc_ln10_fu_162_p1;
wire   [31:0] tmp_5_fu_191_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_s_fu_166_p1;
wire   [1:0] tmp_s_fu_166_p3;
wire  signed [1:0] tmp_s_fu_166_p5;
wire  signed [1:0] tmp_s_fu_166_p7;
wire   [1:0] tmp_5_fu_191_p1;
wire   [1:0] tmp_5_fu_191_p3;
wire  signed [1:0] tmp_5_fu_191_p5;
wire  signed [1:0] tmp_5_fu_191_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 acc_fu_60 = 32'd0;
#0 k_fu_64 = 3'd0;
#0 ap_done_reg = 1'b0;
end

matmul_4x4x4_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U74(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_1_1_reg_263),
    .din1(ap_sig_allocacmp_acc_load_5),
    .ce(1'b1),
    .dout(grp_fu_129_p2)
);

matmul_4x4x4_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U75(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_fu_166_p11),
    .din1(tmp_5_fu_191_p11),
    .ce(1'b1),
    .dout(grp_fu_133_p2)
);

(* dissolve_hierarchy = "yes" *) matmul_4x4x4_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U76(
    .din0(bitcast_ln12_20),
    .din1(bitcast_ln12_21),
    .din2(bitcast_ln12_22),
    .din3(bitcast_ln12_23),
    .def(tmp_s_fu_166_p9),
    .sel(trunc_ln10_fu_162_p1),
    .dout(tmp_s_fu_166_p11)
);

(* dissolve_hierarchy = "yes" *) matmul_4x4x4_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U77(
    .din0(bitcast_ln12_8),
    .din1(bitcast_ln12_9),
    .din2(bitcast_ln12_10),
    .din3(bitcast_ln12_11),
    .def(tmp_5_fu_191_p9),
    .sel(trunc_ln10_fu_162_p1),
    .dout(tmp_5_fu_191_p11)
);

matmul_4x4x4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_fu_60 <= acc_13;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            acc_fu_60 <= grp_fu_129_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln10_fu_150_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_64 <= add_ln10_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_64 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln10_reg_249 <= icmp_ln10_fu_150_p2;
        icmp_ln10_reg_249_pp0_iter1_reg <= icmp_ln10_reg_249;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln10_reg_249_pp0_iter2_reg <= icmp_ln10_reg_249_pp0_iter1_reg;
        icmp_ln10_reg_249_pp0_iter3_reg <= icmp_ln10_reg_249_pp0_iter2_reg;
        mul_1_1_reg_263 <= grp_fu_133_p2;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_249_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        acc_17_out_ap_vld = 1'b1;
    end else begin
        acc_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_150_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_sig_allocacmp_acc_load_5 = grp_fu_129_p2;
    end else begin
        ap_sig_allocacmp_acc_load_5 = acc_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_5 = 3'd0;
    end else begin
        ap_sig_allocacmp_k_5 = k_fu_64;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_17_out = acc_fu_60;

assign add_ln10_fu_156_p2 = (ap_sig_allocacmp_k_5 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln10_fu_150_p2 = ((ap_sig_allocacmp_k_5 == 3'd4) ? 1'b1 : 1'b0);

assign tmp_5_fu_191_p9 = 'bx;

assign tmp_s_fu_166_p9 = 'bx;

assign trunc_ln10_fu_162_p1 = ap_sig_allocacmp_k_5[1:0];

endmodule //matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35
