# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/steven-studio/systolic-mlir/hls/multi_200t/_fp_beat/rtl_fp/pe_timing.xdc

# XDC: /home/steven-studio/systolic-mlir/hls/multi_200t/_fp_beat/rtl_fp/nexys_video_uart.xdc

# IP: ip/floating_point_add_0/floating_point_add_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_add_0 || ORIG_REF_NAME==floating_point_add_0} -quiet] -quiet

# IP: ip/floating_point_mul_0/floating_point_mul_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_mul_0 || ORIG_REF_NAME==floating_point_mul_0} -quiet] -quiet
