-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matmul_4x4x4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    arg0_0_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_0_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_0_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_0_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_1_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_1_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_1_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_1_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_2_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_2_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_2_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_2_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_3_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_3_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_3_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg0_3_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_0_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_0_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_0_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_0_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_1_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_1_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_1_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_1_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_2_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_2_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_2_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_2_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_3_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_3_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_3_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg1_3_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_0_0_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_0_0_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_0_0_o_ap_vld : OUT STD_LOGIC;
    arg2_0_1_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_0_1_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_0_1_o_ap_vld : OUT STD_LOGIC;
    arg2_0_2_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_0_2_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_0_2_o_ap_vld : OUT STD_LOGIC;
    arg2_0_3_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_0_3_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_0_3_o_ap_vld : OUT STD_LOGIC;
    arg2_1_0_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_1_0_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_1_0_o_ap_vld : OUT STD_LOGIC;
    arg2_1_1_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_1_1_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_1_1_o_ap_vld : OUT STD_LOGIC;
    arg2_1_2_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_1_2_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_1_2_o_ap_vld : OUT STD_LOGIC;
    arg2_1_3_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_1_3_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_1_3_o_ap_vld : OUT STD_LOGIC;
    arg2_2_0_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_2_0_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_2_0_o_ap_vld : OUT STD_LOGIC;
    arg2_2_1_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_2_1_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_2_1_o_ap_vld : OUT STD_LOGIC;
    arg2_2_2_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_2_2_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_2_2_o_ap_vld : OUT STD_LOGIC;
    arg2_2_3_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_2_3_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_2_3_o_ap_vld : OUT STD_LOGIC;
    arg2_3_0_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_3_0_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_3_0_o_ap_vld : OUT STD_LOGIC;
    arg2_3_1_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_3_1_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_3_1_o_ap_vld : OUT STD_LOGIC;
    arg2_3_2_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_3_2_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_3_2_o_ap_vld : OUT STD_LOGIC;
    arg2_3_3_i : IN STD_LOGIC_VECTOR (31 downto 0);
    arg2_3_3_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    arg2_3_3_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of matmul_4x4x4 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matmul_4x4x4_matmul_4x4x4,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=46.744000,HLS_SYN_LAT=12,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=8979,HLS_SYN_LUT=13366,HLS_VERSION=2026_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal acc_fu_838_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_reg_1398 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_fu_843_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_reg_1403 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_1_fu_851_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_1_reg_1411 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_2_fu_859_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_2_reg_1419 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_3_fu_867_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_3_reg_1427 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_4_fu_875_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_4_reg_1435 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_5_fu_883_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_5_reg_1443 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_6_fu_891_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_6_reg_1451 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_7_fu_899_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_7_reg_1459 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_15_fu_907_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_15_reg_1467 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_8_fu_912_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_8_reg_1472 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_9_fu_920_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_9_reg_1480 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_10_fu_928_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_10_reg_1488 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_11_fu_936_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_11_reg_1496 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_17_fu_944_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_17_reg_1504 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_12_fu_949_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_12_reg_1509 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_13_fu_957_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_13_reg_1517 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_14_fu_965_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_14_reg_1525 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_15_fu_973_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_15_reg_1533 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_18_fu_981_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_18_reg_1541 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_16_fu_986_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_16_reg_1546 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_17_fu_994_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_17_reg_1554 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_18_fu_1002_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_18_reg_1562 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_19_fu_1010_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_19_reg_1570 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_20_fu_1018_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_20_reg_1578 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_20_fu_1023_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_20_reg_1583 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_21_fu_1031_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_21_reg_1591 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_22_fu_1039_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_22_reg_1599 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_23_fu_1047_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_23_reg_1607 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_21_fu_1055_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_21_reg_1615 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_23_fu_1060_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_23_reg_1620 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_24_fu_1065_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_24_reg_1625 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_26_fu_1070_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_26_reg_1630 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_24_fu_1075_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_24_reg_1635 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_25_fu_1083_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_25_reg_1643 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_26_fu_1091_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_26_reg_1651 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_27_fu_1099_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_27_reg_1659 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_27_fu_1107_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_27_reg_1667 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_28_fu_1112_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_28_reg_1672 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_29_fu_1117_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_29_reg_1677 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_30_fu_1122_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_30_reg_1682 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_28_fu_1127_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_28_reg_1687 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_29_fu_1135_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_29_reg_1695 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_30_fu_1143_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_30_reg_1703 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_31_fu_1151_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln12_31_reg_1711 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_31_fu_1159_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_31_reg_1719 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_32_fu_1164_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_32_reg_1724 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_33_fu_1169_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_33_reg_1729 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_done : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_idle : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_ready : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out_ap_vld : STD_LOGIC;
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg : STD_LOGIC := '0';
    signal grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_9 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_10 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_11 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_5_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_12 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_13 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_14 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_15 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_8_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_16 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_17 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_18 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_19 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_11_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_10 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_20 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_21 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_22 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_23 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_14_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_13 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_20 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_21 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_22 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_23 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_9 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_10 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_11 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_17_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_17_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_16 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_20 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_21 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_22 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_23 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_12 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_13 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_14 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_15 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_20_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_20_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_19 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_20 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_21 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_22 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_23 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_16 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_17 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_18 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_19 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_23_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_23_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_22 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_24 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_25 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_26 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_27 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_26_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_26_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_25 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_24 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_25 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_26 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_27 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_9 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_10 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_11 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_29_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_29_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_28 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_24 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_25 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_26 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_27 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_12 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_13 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_14 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_15 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_32_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_32_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_31 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_24 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_25 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_26 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_27 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_16 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_17 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_18 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_19 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_35_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_35_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_34 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_28 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_29 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_30 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_31 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_38_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_38_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_37 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_28 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_29 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_30 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_31 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_9 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_10 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_11 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_41_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_41_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_40 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_28 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_29 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_30 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_31 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_12 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_13 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_14 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_15 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_44_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_44_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_43 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_28 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_29 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_30 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_31 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_16 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_17 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_18 : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln12_19 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_46_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_46_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_ready,
        acc => acc_reg_1398,
        bitcast_ln12 => bitcast_ln12_reg_1403,
        bitcast_ln12_1 => bitcast_ln12_1_reg_1411,
        bitcast_ln12_2 => bitcast_ln12_2_reg_1419,
        bitcast_ln12_3 => bitcast_ln12_3_reg_1427,
        bitcast_ln12_4 => bitcast_ln12_4_reg_1435,
        bitcast_ln12_5 => bitcast_ln12_5_reg_1443,
        bitcast_ln12_6 => bitcast_ln12_6_reg_1451,
        bitcast_ln12_7 => bitcast_ln12_7_reg_1459,
        acc_2_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out,
        acc_2_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_ready,
        acc_1 => acc_15_reg_1467,
        bitcast_ln12 => bitcast_ln12_reg_1403,
        bitcast_ln12_1 => bitcast_ln12_1_reg_1411,
        bitcast_ln12_2 => bitcast_ln12_2_reg_1419,
        bitcast_ln12_3 => bitcast_ln12_3_reg_1427,
        bitcast_ln12_8 => bitcast_ln12_8_reg_1472,
        bitcast_ln12_9 => bitcast_ln12_9_reg_1480,
        bitcast_ln12_10 => bitcast_ln12_10_reg_1488,
        bitcast_ln12_11 => bitcast_ln12_11_reg_1496,
        acc_5_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out,
        acc_5_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_ready,
        acc_4 => acc_17_reg_1504,
        bitcast_ln12 => bitcast_ln12_reg_1403,
        bitcast_ln12_1 => bitcast_ln12_1_reg_1411,
        bitcast_ln12_2 => bitcast_ln12_2_reg_1419,
        bitcast_ln12_3 => bitcast_ln12_3_reg_1427,
        bitcast_ln12_12 => bitcast_ln12_12_reg_1509,
        bitcast_ln12_13 => bitcast_ln12_13_reg_1517,
        bitcast_ln12_14 => bitcast_ln12_14_reg_1525,
        bitcast_ln12_15 => bitcast_ln12_15_reg_1533,
        acc_8_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out,
        acc_8_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_ready,
        acc_7 => acc_18_reg_1541,
        bitcast_ln12 => bitcast_ln12_reg_1403,
        bitcast_ln12_1 => bitcast_ln12_1_reg_1411,
        bitcast_ln12_2 => bitcast_ln12_2_reg_1419,
        bitcast_ln12_3 => bitcast_ln12_3_reg_1427,
        bitcast_ln12_16 => bitcast_ln12_16_reg_1546,
        bitcast_ln12_17 => bitcast_ln12_17_reg_1554,
        bitcast_ln12_18 => bitcast_ln12_18_reg_1562,
        bitcast_ln12_19 => bitcast_ln12_19_reg_1570,
        acc_11_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out,
        acc_11_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_ready,
        acc_10 => acc_20_reg_1578,
        bitcast_ln12_20 => bitcast_ln12_20_reg_1583,
        bitcast_ln12_21 => bitcast_ln12_21_reg_1591,
        bitcast_ln12_22 => bitcast_ln12_22_reg_1599,
        bitcast_ln12_23 => bitcast_ln12_23_reg_1607,
        bitcast_ln12_4 => bitcast_ln12_4_reg_1435,
        bitcast_ln12_5 => bitcast_ln12_5_reg_1443,
        bitcast_ln12_6 => bitcast_ln12_6_reg_1451,
        bitcast_ln12_7 => bitcast_ln12_7_reg_1459,
        acc_14_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out,
        acc_14_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_ready,
        acc_13 => acc_21_reg_1615,
        bitcast_ln12_20 => bitcast_ln12_20_reg_1583,
        bitcast_ln12_21 => bitcast_ln12_21_reg_1591,
        bitcast_ln12_22 => bitcast_ln12_22_reg_1599,
        bitcast_ln12_23 => bitcast_ln12_23_reg_1607,
        bitcast_ln12_8 => bitcast_ln12_8_reg_1472,
        bitcast_ln12_9 => bitcast_ln12_9_reg_1480,
        bitcast_ln12_10 => bitcast_ln12_10_reg_1488,
        bitcast_ln12_11 => bitcast_ln12_11_reg_1496,
        acc_17_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out,
        acc_17_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_ready,
        acc_16 => acc_23_reg_1620,
        bitcast_ln12_20 => bitcast_ln12_20_reg_1583,
        bitcast_ln12_21 => bitcast_ln12_21_reg_1591,
        bitcast_ln12_22 => bitcast_ln12_22_reg_1599,
        bitcast_ln12_23 => bitcast_ln12_23_reg_1607,
        bitcast_ln12_12 => bitcast_ln12_12_reg_1509,
        bitcast_ln12_13 => bitcast_ln12_13_reg_1517,
        bitcast_ln12_14 => bitcast_ln12_14_reg_1525,
        bitcast_ln12_15 => bitcast_ln12_15_reg_1533,
        acc_20_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out,
        acc_20_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_ready,
        acc_19 => acc_24_reg_1625,
        bitcast_ln12_20 => bitcast_ln12_20_reg_1583,
        bitcast_ln12_21 => bitcast_ln12_21_reg_1591,
        bitcast_ln12_22 => bitcast_ln12_22_reg_1599,
        bitcast_ln12_23 => bitcast_ln12_23_reg_1607,
        bitcast_ln12_16 => bitcast_ln12_16_reg_1546,
        bitcast_ln12_17 => bitcast_ln12_17_reg_1554,
        bitcast_ln12_18 => bitcast_ln12_18_reg_1562,
        bitcast_ln12_19 => bitcast_ln12_19_reg_1570,
        acc_23_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out,
        acc_23_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_ready,
        acc_22 => acc_26_reg_1630,
        bitcast_ln12_24 => bitcast_ln12_24_reg_1635,
        bitcast_ln12_25 => bitcast_ln12_25_reg_1643,
        bitcast_ln12_26 => bitcast_ln12_26_reg_1651,
        bitcast_ln12_27 => bitcast_ln12_27_reg_1659,
        bitcast_ln12_4 => bitcast_ln12_4_reg_1435,
        bitcast_ln12_5 => bitcast_ln12_5_reg_1443,
        bitcast_ln12_6 => bitcast_ln12_6_reg_1451,
        bitcast_ln12_7 => bitcast_ln12_7_reg_1459,
        acc_26_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out,
        acc_26_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_ready,
        acc_25 => acc_27_reg_1667,
        bitcast_ln12_24 => bitcast_ln12_24_reg_1635,
        bitcast_ln12_25 => bitcast_ln12_25_reg_1643,
        bitcast_ln12_26 => bitcast_ln12_26_reg_1651,
        bitcast_ln12_27 => bitcast_ln12_27_reg_1659,
        bitcast_ln12_8 => bitcast_ln12_8_reg_1472,
        bitcast_ln12_9 => bitcast_ln12_9_reg_1480,
        bitcast_ln12_10 => bitcast_ln12_10_reg_1488,
        bitcast_ln12_11 => bitcast_ln12_11_reg_1496,
        acc_29_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out,
        acc_29_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_ready,
        acc_28 => acc_28_reg_1672,
        bitcast_ln12_24 => bitcast_ln12_24_reg_1635,
        bitcast_ln12_25 => bitcast_ln12_25_reg_1643,
        bitcast_ln12_26 => bitcast_ln12_26_reg_1651,
        bitcast_ln12_27 => bitcast_ln12_27_reg_1659,
        bitcast_ln12_12 => bitcast_ln12_12_reg_1509,
        bitcast_ln12_13 => bitcast_ln12_13_reg_1517,
        bitcast_ln12_14 => bitcast_ln12_14_reg_1525,
        bitcast_ln12_15 => bitcast_ln12_15_reg_1533,
        acc_32_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out,
        acc_32_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_ready,
        acc_31 => acc_29_reg_1677,
        bitcast_ln12_24 => bitcast_ln12_24_reg_1635,
        bitcast_ln12_25 => bitcast_ln12_25_reg_1643,
        bitcast_ln12_26 => bitcast_ln12_26_reg_1651,
        bitcast_ln12_27 => bitcast_ln12_27_reg_1659,
        bitcast_ln12_16 => bitcast_ln12_16_reg_1546,
        bitcast_ln12_17 => bitcast_ln12_17_reg_1554,
        bitcast_ln12_18 => bitcast_ln12_18_reg_1562,
        bitcast_ln12_19 => bitcast_ln12_19_reg_1570,
        acc_35_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out,
        acc_35_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_ready,
        acc_34 => acc_30_reg_1682,
        bitcast_ln12_28 => bitcast_ln12_28_reg_1687,
        bitcast_ln12_29 => bitcast_ln12_29_reg_1695,
        bitcast_ln12_30 => bitcast_ln12_30_reg_1703,
        bitcast_ln12_31 => bitcast_ln12_31_reg_1711,
        bitcast_ln12_4 => bitcast_ln12_4_reg_1435,
        bitcast_ln12_5 => bitcast_ln12_5_reg_1443,
        bitcast_ln12_6 => bitcast_ln12_6_reg_1451,
        bitcast_ln12_7 => bitcast_ln12_7_reg_1459,
        acc_38_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out,
        acc_38_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_ready,
        acc_37 => acc_31_reg_1719,
        bitcast_ln12_28 => bitcast_ln12_28_reg_1687,
        bitcast_ln12_29 => bitcast_ln12_29_reg_1695,
        bitcast_ln12_30 => bitcast_ln12_30_reg_1703,
        bitcast_ln12_31 => bitcast_ln12_31_reg_1711,
        bitcast_ln12_8 => bitcast_ln12_8_reg_1472,
        bitcast_ln12_9 => bitcast_ln12_9_reg_1480,
        bitcast_ln12_10 => bitcast_ln12_10_reg_1488,
        bitcast_ln12_11 => bitcast_ln12_11_reg_1496,
        acc_41_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out,
        acc_41_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_ready,
        acc_40 => acc_32_reg_1724,
        bitcast_ln12_28 => bitcast_ln12_28_reg_1687,
        bitcast_ln12_29 => bitcast_ln12_29_reg_1695,
        bitcast_ln12_30 => bitcast_ln12_30_reg_1703,
        bitcast_ln12_31 => bitcast_ln12_31_reg_1711,
        bitcast_ln12_12 => bitcast_ln12_12_reg_1509,
        bitcast_ln12_13 => bitcast_ln12_13_reg_1517,
        bitcast_ln12_14 => bitcast_ln12_14_reg_1525,
        bitcast_ln12_15 => bitcast_ln12_15_reg_1533,
        acc_44_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out,
        acc_44_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out_ap_vld);

    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824 : component matmul_4x4x4_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start,
        ap_done => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_done,
        ap_idle => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_idle,
        ap_ready => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_ready,
        acc_43 => acc_33_reg_1729,
        bitcast_ln12_28 => bitcast_ln12_28_reg_1687,
        bitcast_ln12_29 => bitcast_ln12_29_reg_1695,
        bitcast_ln12_30 => bitcast_ln12_30_reg_1703,
        bitcast_ln12_31 => bitcast_ln12_31_reg_1711,
        bitcast_ln12_16 => bitcast_ln12_16_reg_1546,
        bitcast_ln12_17 => bitcast_ln12_17_reg_1554,
        bitcast_ln12_18 => bitcast_ln12_18_reg_1562,
        bitcast_ln12_19 => bitcast_ln12_19_reg_1570,
        acc_46_out => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out,
        acc_46_out_ap_vld => grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                acc_15_reg_1467 <= acc_15_fu_907_p1;
                acc_17_reg_1504 <= acc_17_fu_944_p1;
                acc_18_reg_1541 <= acc_18_fu_981_p1;
                acc_20_reg_1578 <= acc_20_fu_1018_p1;
                acc_21_reg_1615 <= acc_21_fu_1055_p1;
                acc_23_reg_1620 <= acc_23_fu_1060_p1;
                acc_24_reg_1625 <= acc_24_fu_1065_p1;
                acc_26_reg_1630 <= acc_26_fu_1070_p1;
                acc_27_reg_1667 <= acc_27_fu_1107_p1;
                acc_28_reg_1672 <= acc_28_fu_1112_p1;
                acc_29_reg_1677 <= acc_29_fu_1117_p1;
                acc_30_reg_1682 <= acc_30_fu_1122_p1;
                acc_31_reg_1719 <= acc_31_fu_1159_p1;
                acc_32_reg_1724 <= acc_32_fu_1164_p1;
                acc_33_reg_1729 <= acc_33_fu_1169_p1;
                acc_reg_1398 <= acc_fu_838_p1;
                bitcast_ln12_10_reg_1488 <= bitcast_ln12_10_fu_928_p1;
                bitcast_ln12_11_reg_1496 <= bitcast_ln12_11_fu_936_p1;
                bitcast_ln12_12_reg_1509 <= bitcast_ln12_12_fu_949_p1;
                bitcast_ln12_13_reg_1517 <= bitcast_ln12_13_fu_957_p1;
                bitcast_ln12_14_reg_1525 <= bitcast_ln12_14_fu_965_p1;
                bitcast_ln12_15_reg_1533 <= bitcast_ln12_15_fu_973_p1;
                bitcast_ln12_16_reg_1546 <= bitcast_ln12_16_fu_986_p1;
                bitcast_ln12_17_reg_1554 <= bitcast_ln12_17_fu_994_p1;
                bitcast_ln12_18_reg_1562 <= bitcast_ln12_18_fu_1002_p1;
                bitcast_ln12_19_reg_1570 <= bitcast_ln12_19_fu_1010_p1;
                bitcast_ln12_1_reg_1411 <= bitcast_ln12_1_fu_851_p1;
                bitcast_ln12_20_reg_1583 <= bitcast_ln12_20_fu_1023_p1;
                bitcast_ln12_21_reg_1591 <= bitcast_ln12_21_fu_1031_p1;
                bitcast_ln12_22_reg_1599 <= bitcast_ln12_22_fu_1039_p1;
                bitcast_ln12_23_reg_1607 <= bitcast_ln12_23_fu_1047_p1;
                bitcast_ln12_24_reg_1635 <= bitcast_ln12_24_fu_1075_p1;
                bitcast_ln12_25_reg_1643 <= bitcast_ln12_25_fu_1083_p1;
                bitcast_ln12_26_reg_1651 <= bitcast_ln12_26_fu_1091_p1;
                bitcast_ln12_27_reg_1659 <= bitcast_ln12_27_fu_1099_p1;
                bitcast_ln12_28_reg_1687 <= bitcast_ln12_28_fu_1127_p1;
                bitcast_ln12_29_reg_1695 <= bitcast_ln12_29_fu_1135_p1;
                bitcast_ln12_2_reg_1419 <= bitcast_ln12_2_fu_859_p1;
                bitcast_ln12_30_reg_1703 <= bitcast_ln12_30_fu_1143_p1;
                bitcast_ln12_31_reg_1711 <= bitcast_ln12_31_fu_1151_p1;
                bitcast_ln12_3_reg_1427 <= bitcast_ln12_3_fu_867_p1;
                bitcast_ln12_4_reg_1435 <= bitcast_ln12_4_fu_875_p1;
                bitcast_ln12_5_reg_1443 <= bitcast_ln12_5_fu_883_p1;
                bitcast_ln12_6_reg_1451 <= bitcast_ln12_6_fu_891_p1;
                bitcast_ln12_7_reg_1459 <= bitcast_ln12_7_fu_899_p1;
                bitcast_ln12_8_reg_1472 <= bitcast_ln12_8_fu_912_p1;
                bitcast_ln12_9_reg_1480 <= bitcast_ln12_9_fu_920_p1;
                bitcast_ln12_reg_1403 <= bitcast_ln12_fu_843_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    acc_15_fu_907_p1 <= arg2_0_1_i;
    acc_17_fu_944_p1 <= arg2_0_2_i;
    acc_18_fu_981_p1 <= arg2_0_3_i;
    acc_20_fu_1018_p1 <= arg2_1_0_i;
    acc_21_fu_1055_p1 <= arg2_1_1_i;
    acc_23_fu_1060_p1 <= arg2_1_2_i;
    acc_24_fu_1065_p1 <= arg2_1_3_i;
    acc_26_fu_1070_p1 <= arg2_2_0_i;
    acc_27_fu_1107_p1 <= arg2_2_1_i;
    acc_28_fu_1112_p1 <= arg2_2_2_i;
    acc_29_fu_1117_p1 <= arg2_2_3_i;
    acc_30_fu_1122_p1 <= arg2_3_0_i;
    acc_31_fu_1159_p1 <= arg2_3_1_i;
    acc_32_fu_1164_p1 <= arg2_3_2_i;
    acc_33_fu_1169_p1 <= arg2_3_3_i;
    acc_fu_838_p1 <= arg2_0_0_i;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_block_state2_on_subcall_done_assign_proc : process(grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_done, grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_done 
    = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_done = ap_const_logic_0) or (grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    arg2_0_0_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_acc_2_out;

    arg2_0_0_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_0_0_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_0_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_0_1_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_acc_5_out;

    arg2_0_1_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_0_1_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_0_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_0_2_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_acc_8_out;

    arg2_0_2_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_0_2_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_0_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_0_3_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_acc_11_out;

    arg2_0_3_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_0_3_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_0_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_1_0_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_acc_14_out;

    arg2_1_0_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_1_0_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_1_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_1_1_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_acc_17_out;

    arg2_1_1_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_1_1_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_1_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_1_2_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_acc_20_out;

    arg2_1_2_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_1_2_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_1_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_1_3_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_acc_23_out;

    arg2_1_3_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_1_3_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_1_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_2_0_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_acc_26_out;

    arg2_2_0_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_2_0_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_2_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_2_1_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_acc_29_out;

    arg2_2_1_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_2_1_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_2_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_2_2_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_acc_32_out;

    arg2_2_2_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_2_2_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_2_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_2_3_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_acc_35_out;

    arg2_2_3_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_2_3_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_2_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_3_0_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_acc_38_out;

    arg2_3_0_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_3_0_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_3_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_3_1_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_acc_41_out;

    arg2_3_1_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_3_1_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_3_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_3_2_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_acc_44_out;

    arg2_3_2_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_3_2_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_3_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arg2_3_3_o <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_acc_46_out;

    arg2_3_3_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arg2_3_3_o_ap_vld <= ap_const_logic_1;
        else 
            arg2_3_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln12_10_fu_928_p1 <= arg1_2_1;
    bitcast_ln12_11_fu_936_p1 <= arg1_3_1;
    bitcast_ln12_12_fu_949_p1 <= arg1_0_2;
    bitcast_ln12_13_fu_957_p1 <= arg1_1_2;
    bitcast_ln12_14_fu_965_p1 <= arg1_2_2;
    bitcast_ln12_15_fu_973_p1 <= arg1_3_2;
    bitcast_ln12_16_fu_986_p1 <= arg1_0_3;
    bitcast_ln12_17_fu_994_p1 <= arg1_1_3;
    bitcast_ln12_18_fu_1002_p1 <= arg1_2_3;
    bitcast_ln12_19_fu_1010_p1 <= arg1_3_3;
    bitcast_ln12_1_fu_851_p1 <= arg0_0_1;
    bitcast_ln12_20_fu_1023_p1 <= arg0_1_0;
    bitcast_ln12_21_fu_1031_p1 <= arg0_1_1;
    bitcast_ln12_22_fu_1039_p1 <= arg0_1_2;
    bitcast_ln12_23_fu_1047_p1 <= arg0_1_3;
    bitcast_ln12_24_fu_1075_p1 <= arg0_2_0;
    bitcast_ln12_25_fu_1083_p1 <= arg0_2_1;
    bitcast_ln12_26_fu_1091_p1 <= arg0_2_2;
    bitcast_ln12_27_fu_1099_p1 <= arg0_2_3;
    bitcast_ln12_28_fu_1127_p1 <= arg0_3_0;
    bitcast_ln12_29_fu_1135_p1 <= arg0_3_1;
    bitcast_ln12_2_fu_859_p1 <= arg0_0_2;
    bitcast_ln12_30_fu_1143_p1 <= arg0_3_2;
    bitcast_ln12_31_fu_1151_p1 <= arg0_3_3;
    bitcast_ln12_3_fu_867_p1 <= arg0_0_3;
    bitcast_ln12_4_fu_875_p1 <= arg1_0_0;
    bitcast_ln12_5_fu_883_p1 <= arg1_1_0;
    bitcast_ln12_6_fu_891_p1 <= arg1_2_0;
    bitcast_ln12_7_fu_899_p1 <= arg1_3_0;
    bitcast_ln12_8_fu_912_p1 <= arg1_0_1;
    bitcast_ln12_9_fu_920_p1 <= arg1_1_1;
    bitcast_ln12_fu_843_p1 <= arg0_0_0;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740_ap_start_reg;
    grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start <= grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614_ap_start_reg;
end behav;
