

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "7", "13", "19", "25", "31", "37", "43", "49", "55", "61", "67", "73", "79", "85", "91"],
		"CDFG" : "matmul_4x4x4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "12", "EstimateLatencyMax" : "12",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "arg0_0_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_0_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_0_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_0_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_1_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_1_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_1_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_1_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_2_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_2_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_2_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_2_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_3_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_3_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_3_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg0_3_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_0_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_0_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_0_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_0_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_1_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_1_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_1_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_1_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_2_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_2_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_2_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_2_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_3_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_3_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_3_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg1_3_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "arg2_0_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_0_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_0_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_0_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_1_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_1_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_1_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_1_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_2_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_2_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_2_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_2_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_3_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_3_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_3_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "arg2_3_3", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_2_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614.fadd_32ns_32ns_32_2_full_dsp_1_U1", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614.fmul_32ns_32ns_32_4_full_dsp_1_U2", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614.sparsemux_9_2_32_1_1_U3", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614.sparsemux_9_2_32_1_1_U4", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_3_fu_614.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628", "Parent" : "0", "Child" : ["8", "9", "10", "11", "12"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_31",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_5_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628.fadd_32ns_32ns_32_2_full_dsp_1_U18", "Parent" : "7"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628.fmul_32ns_32ns_32_4_full_dsp_1_U19", "Parent" : "7"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628.sparsemux_9_2_32_1_1_U20", "Parent" : "7"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628.sparsemux_9_2_32_1_1_U21", "Parent" : "7"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_31_fu_628.flow_control_loop_pipe_sequential_init_U", "Parent" : "7"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642", "Parent" : "0", "Child" : ["14", "15", "16", "17", "18"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_32",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_8_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642.fadd_32ns_32ns_32_2_full_dsp_1_U32", "Parent" : "13"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642.fmul_32ns_32ns_32_4_full_dsp_1_U33", "Parent" : "13"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642.sparsemux_9_2_32_1_1_U34", "Parent" : "13"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642.sparsemux_9_2_32_1_1_U35", "Parent" : "13"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_32_fu_642.flow_control_loop_pipe_sequential_init_U", "Parent" : "13"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656", "Parent" : "0", "Child" : ["20", "21", "22", "23", "24"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_33",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_11_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656.fadd_32ns_32ns_32_2_full_dsp_1_U46", "Parent" : "19"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656.fmul_32ns_32ns_32_4_full_dsp_1_U47", "Parent" : "19"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656.sparsemux_9_2_32_1_1_U48", "Parent" : "19"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656.sparsemux_9_2_32_1_1_U49", "Parent" : "19"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_33_fu_656.flow_control_loop_pipe_sequential_init_U", "Parent" : "19"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670", "Parent" : "0", "Child" : ["26", "27", "28", "29", "30"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_34",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_23", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_14_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670.fadd_32ns_32ns_32_2_full_dsp_1_U60", "Parent" : "25"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670.fmul_32ns_32ns_32_4_full_dsp_1_U61", "Parent" : "25"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670.sparsemux_9_2_32_1_1_U62", "Parent" : "25"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670.sparsemux_9_2_32_1_1_U63", "Parent" : "25"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_34_fu_670.flow_control_loop_pipe_sequential_init_U", "Parent" : "25"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684", "Parent" : "0", "Child" : ["32", "33", "34", "35", "36"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_35",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_23", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_17_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684.fadd_32ns_32ns_32_2_full_dsp_1_U74", "Parent" : "31"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684.fmul_32ns_32ns_32_4_full_dsp_1_U75", "Parent" : "31"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684.sparsemux_9_2_32_1_1_U76", "Parent" : "31"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684.sparsemux_9_2_32_1_1_U77", "Parent" : "31"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_35_fu_684.flow_control_loop_pipe_sequential_init_U", "Parent" : "31"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698", "Parent" : "0", "Child" : ["38", "39", "40", "41", "42"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_36",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_23", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_20_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698.fadd_32ns_32ns_32_2_full_dsp_1_U88", "Parent" : "37"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698.fmul_32ns_32ns_32_4_full_dsp_1_U89", "Parent" : "37"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698.sparsemux_9_2_32_1_1_U90", "Parent" : "37"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698.sparsemux_9_2_32_1_1_U91", "Parent" : "37"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_36_fu_698.flow_control_loop_pipe_sequential_init_U", "Parent" : "37"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712", "Parent" : "0", "Child" : ["44", "45", "46", "47", "48"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_37",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_23", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_23_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712.fadd_32ns_32ns_32_2_full_dsp_1_U102", "Parent" : "43"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712.fmul_32ns_32ns_32_4_full_dsp_1_U103", "Parent" : "43"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712.sparsemux_9_2_32_1_1_U104", "Parent" : "43"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712.sparsemux_9_2_32_1_1_U105", "Parent" : "43"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_37_fu_712.flow_control_loop_pipe_sequential_init_U", "Parent" : "43"},
	{"ID" : "49", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726", "Parent" : "0", "Child" : ["50", "51", "52", "53", "54"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_38",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_24", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_25", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_27", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_26_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726.fadd_32ns_32ns_32_2_full_dsp_1_U116", "Parent" : "49"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726.fmul_32ns_32ns_32_4_full_dsp_1_U117", "Parent" : "49"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726.sparsemux_9_2_32_1_1_U118", "Parent" : "49"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726.sparsemux_9_2_32_1_1_U119", "Parent" : "49"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_38_fu_726.flow_control_loop_pipe_sequential_init_U", "Parent" : "49"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740", "Parent" : "0", "Child" : ["56", "57", "58", "59", "60"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_39",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_25", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_24", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_25", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_27", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_29_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740.fadd_32ns_32ns_32_2_full_dsp_1_U130", "Parent" : "55"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740.fmul_32ns_32ns_32_4_full_dsp_1_U131", "Parent" : "55"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740.sparsemux_9_2_32_1_1_U132", "Parent" : "55"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740.sparsemux_9_2_32_1_1_U133", "Parent" : "55"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_39_fu_740.flow_control_loop_pipe_sequential_init_U", "Parent" : "55"},
	{"ID" : "61", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754", "Parent" : "0", "Child" : ["62", "63", "64", "65", "66"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_310",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_24", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_25", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_27", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_32_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754.fadd_32ns_32ns_32_2_full_dsp_1_U144", "Parent" : "61"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754.fmul_32ns_32ns_32_4_full_dsp_1_U145", "Parent" : "61"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754.sparsemux_9_2_32_1_1_U146", "Parent" : "61"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754.sparsemux_9_2_32_1_1_U147", "Parent" : "61"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_310_fu_754.flow_control_loop_pipe_sequential_init_U", "Parent" : "61"},
	{"ID" : "67", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768", "Parent" : "0", "Child" : ["68", "69", "70", "71", "72"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_311",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_31", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_24", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_25", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_27", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_35_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768.fadd_32ns_32ns_32_2_full_dsp_1_U158", "Parent" : "67"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768.fmul_32ns_32ns_32_4_full_dsp_1_U159", "Parent" : "67"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768.sparsemux_9_2_32_1_1_U160", "Parent" : "67"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768.sparsemux_9_2_32_1_1_U161", "Parent" : "67"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_311_fu_768.flow_control_loop_pipe_sequential_init_U", "Parent" : "67"},
	{"ID" : "73", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782", "Parent" : "0", "Child" : ["74", "75", "76", "77", "78"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_312",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_34", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_29", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_31", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_38_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782.fadd_32ns_32ns_32_2_full_dsp_1_U172", "Parent" : "73"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782.fmul_32ns_32ns_32_4_full_dsp_1_U173", "Parent" : "73"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782.sparsemux_9_2_32_1_1_U174", "Parent" : "73"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782.sparsemux_9_2_32_1_1_U175", "Parent" : "73"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_312_fu_782.flow_control_loop_pipe_sequential_init_U", "Parent" : "73"},
	{"ID" : "79", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796", "Parent" : "0", "Child" : ["80", "81", "82", "83", "84"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_313",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_37", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_29", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_31", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_41_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796.fadd_32ns_32ns_32_2_full_dsp_1_U186", "Parent" : "79"},
	{"ID" : "81", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796.fmul_32ns_32ns_32_4_full_dsp_1_U187", "Parent" : "79"},
	{"ID" : "82", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796.sparsemux_9_2_32_1_1_U188", "Parent" : "79"},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796.sparsemux_9_2_32_1_1_U189", "Parent" : "79"},
	{"ID" : "84", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_313_fu_796.flow_control_loop_pipe_sequential_init_U", "Parent" : "79"},
	{"ID" : "85", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810", "Parent" : "0", "Child" : ["86", "87", "88", "89", "90"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_314",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_40", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_29", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_31", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_44_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "86", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810.fadd_32ns_32ns_32_2_full_dsp_1_U200", "Parent" : "85"},
	{"ID" : "87", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810.fmul_32ns_32ns_32_4_full_dsp_1_U201", "Parent" : "85"},
	{"ID" : "88", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810.sparsemux_9_2_32_1_1_U202", "Parent" : "85"},
	{"ID" : "89", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810.sparsemux_9_2_32_1_1_U203", "Parent" : "85"},
	{"ID" : "90", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_314_fu_810.flow_control_loop_pipe_sequential_init_U", "Parent" : "85"},
	{"ID" : "91", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824", "Parent" : "0", "Child" : ["92", "93", "94", "95", "96"],
		"CDFG" : "matmul_4x4x4_Pipeline_VITIS_LOOP_10_315",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_43", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_29", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_31", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitcast_ln12_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_46_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "92", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824.fadd_32ns_32ns_32_2_full_dsp_1_U214", "Parent" : "91"},
	{"ID" : "93", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824.fmul_32ns_32ns_32_4_full_dsp_1_U215", "Parent" : "91"},
	{"ID" : "94", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824.sparsemux_9_2_32_1_1_U216", "Parent" : "91"},
	{"ID" : "95", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824.sparsemux_9_2_32_1_1_U217", "Parent" : "91"},
	{"ID" : "96", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_4x4x4_Pipeline_VITIS_LOOP_10_315_fu_824.flow_control_loop_pipe_sequential_init_U", "Parent" : "91"}]}
