// Auto-generated by gen_matmul_iface.py (4x4) -- 請勿手動修改
module matmul_iface (
    input  wire        ap_clk,
    input  wire        ap_rst,
    input  wire        ap_start,
    output wire        ap_done,
    output wire        ap_idle,
    output wire        ap_ready,
    input  wire [511:0] arg0_flat,
    input  wire [511:0] arg1_flat,
    input  wire [511:0] arg2_in_flat,
    output wire [511:0] arg2_out_flat,
    output wire [15:0]   arg2_vld_flat
);

    wire [31:0] w_arg0_0_0 = arg0_flat[31:0];
    wire [31:0] w_arg0_0_1 = arg0_flat[63:32];
    wire [31:0] w_arg0_0_2 = arg0_flat[95:64];
    wire [31:0] w_arg0_0_3 = arg0_flat[127:96];
    wire [31:0] w_arg0_1_0 = arg0_flat[159:128];
    wire [31:0] w_arg0_1_1 = arg0_flat[191:160];
    wire [31:0] w_arg0_1_2 = arg0_flat[223:192];
    wire [31:0] w_arg0_1_3 = arg0_flat[255:224];
    wire [31:0] w_arg0_2_0 = arg0_flat[287:256];
    wire [31:0] w_arg0_2_1 = arg0_flat[319:288];
    wire [31:0] w_arg0_2_2 = arg0_flat[351:320];
    wire [31:0] w_arg0_2_3 = arg0_flat[383:352];
    wire [31:0] w_arg0_3_0 = arg0_flat[415:384];
    wire [31:0] w_arg0_3_1 = arg0_flat[447:416];
    wire [31:0] w_arg0_3_2 = arg0_flat[479:448];
    wire [31:0] w_arg0_3_3 = arg0_flat[511:480];
    wire [31:0] w_arg1_0_0 = arg1_flat[31:0];
    wire [31:0] w_arg1_0_1 = arg1_flat[63:32];
    wire [31:0] w_arg1_0_2 = arg1_flat[95:64];
    wire [31:0] w_arg1_0_3 = arg1_flat[127:96];
    wire [31:0] w_arg1_1_0 = arg1_flat[159:128];
    wire [31:0] w_arg1_1_1 = arg1_flat[191:160];
    wire [31:0] w_arg1_1_2 = arg1_flat[223:192];
    wire [31:0] w_arg1_1_3 = arg1_flat[255:224];
    wire [31:0] w_arg1_2_0 = arg1_flat[287:256];
    wire [31:0] w_arg1_2_1 = arg1_flat[319:288];
    wire [31:0] w_arg1_2_2 = arg1_flat[351:320];
    wire [31:0] w_arg1_2_3 = arg1_flat[383:352];
    wire [31:0] w_arg1_3_0 = arg1_flat[415:384];
    wire [31:0] w_arg1_3_1 = arg1_flat[447:416];
    wire [31:0] w_arg1_3_2 = arg1_flat[479:448];
    wire [31:0] w_arg1_3_3 = arg1_flat[511:480];
    wire [31:0] w_arg2i_0_0 = arg2_in_flat[31:0];
    wire [31:0] w_arg2i_0_1 = arg2_in_flat[63:32];
    wire [31:0] w_arg2i_0_2 = arg2_in_flat[95:64];
    wire [31:0] w_arg2i_0_3 = arg2_in_flat[127:96];
    wire [31:0] w_arg2i_1_0 = arg2_in_flat[159:128];
    wire [31:0] w_arg2i_1_1 = arg2_in_flat[191:160];
    wire [31:0] w_arg2i_1_2 = arg2_in_flat[223:192];
    wire [31:0] w_arg2i_1_3 = arg2_in_flat[255:224];
    wire [31:0] w_arg2i_2_0 = arg2_in_flat[287:256];
    wire [31:0] w_arg2i_2_1 = arg2_in_flat[319:288];
    wire [31:0] w_arg2i_2_2 = arg2_in_flat[351:320];
    wire [31:0] w_arg2i_2_3 = arg2_in_flat[383:352];
    wire [31:0] w_arg2i_3_0 = arg2_in_flat[415:384];
    wire [31:0] w_arg2i_3_1 = arg2_in_flat[447:416];
    wire [31:0] w_arg2i_3_2 = arg2_in_flat[479:448];
    wire [31:0] w_arg2i_3_3 = arg2_in_flat[511:480];

    wire [31:0] w_arg2o [0:15];
    wire        w_arg2vld [0:15];

    assign arg2_out_flat[31:0] = w_arg2o[0];
    assign arg2_vld_flat[0] = w_arg2vld[0];
    assign arg2_out_flat[63:32] = w_arg2o[1];
    assign arg2_vld_flat[1] = w_arg2vld[1];
    assign arg2_out_flat[95:64] = w_arg2o[2];
    assign arg2_vld_flat[2] = w_arg2vld[2];
    assign arg2_out_flat[127:96] = w_arg2o[3];
    assign arg2_vld_flat[3] = w_arg2vld[3];
    assign arg2_out_flat[159:128] = w_arg2o[4];
    assign arg2_vld_flat[4] = w_arg2vld[4];
    assign arg2_out_flat[191:160] = w_arg2o[5];
    assign arg2_vld_flat[5] = w_arg2vld[5];
    assign arg2_out_flat[223:192] = w_arg2o[6];
    assign arg2_vld_flat[6] = w_arg2vld[6];
    assign arg2_out_flat[255:224] = w_arg2o[7];
    assign arg2_vld_flat[7] = w_arg2vld[7];
    assign arg2_out_flat[287:256] = w_arg2o[8];
    assign arg2_vld_flat[8] = w_arg2vld[8];
    assign arg2_out_flat[319:288] = w_arg2o[9];
    assign arg2_vld_flat[9] = w_arg2vld[9];
    assign arg2_out_flat[351:320] = w_arg2o[10];
    assign arg2_vld_flat[10] = w_arg2vld[10];
    assign arg2_out_flat[383:352] = w_arg2o[11];
    assign arg2_vld_flat[11] = w_arg2vld[11];
    assign arg2_out_flat[415:384] = w_arg2o[12];
    assign arg2_vld_flat[12] = w_arg2vld[12];
    assign arg2_out_flat[447:416] = w_arg2o[13];
    assign arg2_vld_flat[13] = w_arg2vld[13];
    assign arg2_out_flat[479:448] = w_arg2o[14];
    assign arg2_vld_flat[14] = w_arg2vld[14];
    assign arg2_out_flat[511:480] = w_arg2o[15];
    assign arg2_vld_flat[15] = w_arg2vld[15];

    matmul_4x4x4 u_matmul (
        .ap_clk(ap_clk),
        .ap_rst(ap_rst),
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        .arg0_0_0(w_arg0_0_0),
        .arg0_0_1(w_arg0_0_1),
        .arg0_0_2(w_arg0_0_2),
        .arg0_0_3(w_arg0_0_3),
        .arg0_1_0(w_arg0_1_0),
        .arg0_1_1(w_arg0_1_1),
        .arg0_1_2(w_arg0_1_2),
        .arg0_1_3(w_arg0_1_3),
        .arg0_2_0(w_arg0_2_0),
        .arg0_2_1(w_arg0_2_1),
        .arg0_2_2(w_arg0_2_2),
        .arg0_2_3(w_arg0_2_3),
        .arg0_3_0(w_arg0_3_0),
        .arg0_3_1(w_arg0_3_1),
        .arg0_3_2(w_arg0_3_2),
        .arg0_3_3(w_arg0_3_3),
        .arg1_0_0(w_arg1_0_0),
        .arg1_0_1(w_arg1_0_1),
        .arg1_0_2(w_arg1_0_2),
        .arg1_0_3(w_arg1_0_3),
        .arg1_1_0(w_arg1_1_0),
        .arg1_1_1(w_arg1_1_1),
        .arg1_1_2(w_arg1_1_2),
        .arg1_1_3(w_arg1_1_3),
        .arg1_2_0(w_arg1_2_0),
        .arg1_2_1(w_arg1_2_1),
        .arg1_2_2(w_arg1_2_2),
        .arg1_2_3(w_arg1_2_3),
        .arg1_3_0(w_arg1_3_0),
        .arg1_3_1(w_arg1_3_1),
        .arg1_3_2(w_arg1_3_2),
        .arg1_3_3(w_arg1_3_3),
        .arg2_0_0_i(w_arg2i_0_0),
        .arg2_0_0_o(w_arg2o[0]),
        .arg2_0_0_o_ap_vld(w_arg2vld[0]),
        .arg2_0_1_i(w_arg2i_0_1),
        .arg2_0_1_o(w_arg2o[1]),
        .arg2_0_1_o_ap_vld(w_arg2vld[1]),
        .arg2_0_2_i(w_arg2i_0_2),
        .arg2_0_2_o(w_arg2o[2]),
        .arg2_0_2_o_ap_vld(w_arg2vld[2]),
        .arg2_0_3_i(w_arg2i_0_3),
        .arg2_0_3_o(w_arg2o[3]),
        .arg2_0_3_o_ap_vld(w_arg2vld[3]),
        .arg2_1_0_i(w_arg2i_1_0),
        .arg2_1_0_o(w_arg2o[4]),
        .arg2_1_0_o_ap_vld(w_arg2vld[4]),
        .arg2_1_1_i(w_arg2i_1_1),
        .arg2_1_1_o(w_arg2o[5]),
        .arg2_1_1_o_ap_vld(w_arg2vld[5]),
        .arg2_1_2_i(w_arg2i_1_2),
        .arg2_1_2_o(w_arg2o[6]),
        .arg2_1_2_o_ap_vld(w_arg2vld[6]),
        .arg2_1_3_i(w_arg2i_1_3),
        .arg2_1_3_o(w_arg2o[7]),
        .arg2_1_3_o_ap_vld(w_arg2vld[7]),
        .arg2_2_0_i(w_arg2i_2_0),
        .arg2_2_0_o(w_arg2o[8]),
        .arg2_2_0_o_ap_vld(w_arg2vld[8]),
        .arg2_2_1_i(w_arg2i_2_1),
        .arg2_2_1_o(w_arg2o[9]),
        .arg2_2_1_o_ap_vld(w_arg2vld[9]),
        .arg2_2_2_i(w_arg2i_2_2),
        .arg2_2_2_o(w_arg2o[10]),
        .arg2_2_2_o_ap_vld(w_arg2vld[10]),
        .arg2_2_3_i(w_arg2i_2_3),
        .arg2_2_3_o(w_arg2o[11]),
        .arg2_2_3_o_ap_vld(w_arg2vld[11]),
        .arg2_3_0_i(w_arg2i_3_0),
        .arg2_3_0_o(w_arg2o[12]),
        .arg2_3_0_o_ap_vld(w_arg2vld[12]),
        .arg2_3_1_i(w_arg2i_3_1),
        .arg2_3_1_o(w_arg2o[13]),
        .arg2_3_1_o_ap_vld(w_arg2vld[13]),
        .arg2_3_2_i(w_arg2i_3_2),
        .arg2_3_2_o(w_arg2o[14]),
        .arg2_3_2_o_ap_vld(w_arg2vld[14]),
        .arg2_3_3_i(w_arg2i_3_3),
        .arg2_3_3_o(w_arg2o[15]),
        .arg2_3_3_o_ap_vld(w_arg2vld[15])
    );

endmodule