#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2026.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sat Aug 08 12:56:14 CST 2026
# SW Build 6511674 on Tue Jun 16 11:01:26 MDT 2026
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2026.1
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/steven-studio/tools/Xilinx/${SIM_VER_XSIM}/${SIM_VER_XSIM}/data"
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj tb_pe_vlog.prj"
xvlog --incr --relax -L uvm -prj tb_pe_vlog.prj 2>&1 | tee compile.log

# compile VHDL design sources
echo "xvhdl --incr --relax -prj tb_pe_vhdl.prj"
xvhdl --incr --relax -prj tb_pe_vhdl.prj 2>&1 | tee -a compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
