#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2026.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Aug 08 12:56:17 CST 2026
# SW Build 6511674 on Tue Jun 16 11:01:26 MDT 2026
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2026.1
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/steven-studio/tools/Xilinx/${SIM_VER_XSIM}/${SIM_VER_XSIM}/data"
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_16 -L axi_utils_v2_0_12 -L xbip_pipe_v3_0_12 -L xbip_dsp48_wrapper_v3_0_7 -L mult_gen_v12_0_25 -L floating_point_v7_1_22 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_pe_behav xil_defaultlib.tb_pe xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_16 -L axi_utils_v2_0_12 -L xbip_pipe_v3_0_12 -L xbip_dsp48_wrapper_v3_0_7 -L mult_gen_v12_0_25 -L floating_point_v7_1_22 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_pe_behav xil_defaultlib.tb_pe xil_defaultlib.glbl -log elaborate.log

