#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2026.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Aug 08 12:56:25 CST 2026
# SW Build 6511674 on Tue Jun 16 11:01:26 MDT 2026
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2026.1
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim tb_pe_behav -key {Behavioral:sim_1:Functional:tb_pe} -tclbatch tb_pe.tcl -log simulate.log"
xsim tb_pe_behav -key {Behavioral:sim_1:Functional:tb_pe} -tclbatch tb_pe.tcl -log simulate.log

