#ifndef SYSTOLIC_SYSTOLICDIALECT_H
#define SYSTOLIC_SYSTOLICDIALECT_H

#include "mlir/IR/Dialect.h"

// Generated by `add_mlir_dialect(SystolicOps systolic)` (see
// include/Systolic/CMakeLists.txt) from SystolicDialect.td +
// SystolicOps.td. NOTE: not tblgen-verified in this sandbox -- if the
// generated include name differs slightly on your LLVM version, this is
// the line to fix.
#include "Systolic/SystolicOpsDialect.h.inc"

#endif // SYSTOLIC_SYSTOLICDIALECT_H
