#!/usr/bin/env python3
# 自動產生 matmul_iface.v (4x4 版本) -- 把 matmul_4x4x4 的 64 個獨立埠
# 轉換成扁平向量介面,方便外層 UART controller 使用

N = 4  # 矩陣維度

lines = []
lines.append("// Auto-generated by gen_matmul_iface.py (4x4) -- 請勿手動修改")
lines.append("module matmul_iface (")
lines.append("    input  wire        ap_clk,")
lines.append("    input  wire        ap_rst,")
lines.append("    input  wire        ap_start,")
lines.append("    output wire        ap_done,")
lines.append("    output wire        ap_idle,")
lines.append("    output wire        ap_ready,")
lines.append("    input  wire [511:0] arg0_flat,")
lines.append("    input  wire [511:0] arg1_flat,")
lines.append("    input  wire [511:0] arg2_in_flat,")
lines.append("    output wire [511:0] arg2_out_flat,")
lines.append("    output wire [15:0]   arg2_vld_flat")
lines.append(");")
lines.append("")

for i in range(N):
    for j in range(N):
        idx = i*N + j
        lines.append(f"    wire [31:0] w_arg0_{i}_{j} = arg0_flat[{idx*32+31}:{idx*32}];")
for i in range(N):
    for j in range(N):
        idx = i*N + j
        lines.append(f"    wire [31:0] w_arg1_{i}_{j} = arg1_flat[{idx*32+31}:{idx*32}];")
for i in range(N):
    for j in range(N):
        idx = i*N + j
        lines.append(f"    wire [31:0] w_arg2i_{i}_{j} = arg2_in_flat[{idx*32+31}:{idx*32}];")

lines.append("")
lines.append(f"    wire [31:0] w_arg2o [0:{N*N-1}];")
lines.append(f"    wire        w_arg2vld [0:{N*N-1}];")
lines.append("")

for i in range(N):
    for j in range(N):
        idx = i*N + j
        lines.append(f"    assign arg2_out_flat[{idx*32+31}:{idx*32}] = w_arg2o[{idx}];")
        lines.append(f"    assign arg2_vld_flat[{idx}] = w_arg2vld[{idx}];")

lines.append("")
lines.append("    matmul_4x4x4 u_matmul (")
lines.append("        .ap_clk(ap_clk),")
lines.append("        .ap_rst(ap_rst),")
lines.append("        .ap_start(ap_start),")
lines.append("        .ap_done(ap_done),")
lines.append("        .ap_idle(ap_idle),")
lines.append("        .ap_ready(ap_ready),")

conns = []
for i in range(N):
    for j in range(N):
        conns.append(f"        .arg0_{i}_{j}(w_arg0_{i}_{j})")
for i in range(N):
    for j in range(N):
        conns.append(f"        .arg1_{i}_{j}(w_arg1_{i}_{j})")
for i in range(N):
    for j in range(N):
        idx = i*N+j
        conns.append(f"        .arg2_{i}_{j}_i(w_arg2i_{i}_{j})")
        conns.append(f"        .arg2_{i}_{j}_o(w_arg2o[{idx}])")
        conns.append(f"        .arg2_{i}_{j}_o_ap_vld(w_arg2vld[{idx}])")

lines.append(",\n".join(conns))
lines.append("    );")
lines.append("")
lines.append("endmodule")

with open("matmul_iface.v", "w") as f:
    f.write("\n".join(lines))

print("已產生 matmul_iface.v (4x4),共", len(lines), "行")
