// Auto-generated by gen_matmul_iface_fold_new.py (8x8, K_MAX=64, MT=2, NT=2)
// -- 請勿手動修改
//
// Runtime-K interface wrapper. A and B live in RAM inside this module;
// the UART side fills them through one linear write port, and the core
// reads them through 2*N independent ap_memory ports.
//
// WRITE ADDRESS LAYOUT
//   ab_waddr[9:7] = bank  (row of A, or column of B)
//   ab_waddr[6:6] = fold  (A uses the low 1, B the low 1)
//   ab_waddr[5:0] = word  (position along K)
// The host streams, for each fold, row 0 words 0..K-1, then row 1,
// and so on. Words at or beyond K are never read by the core -- it
// stops the time loop at K + R + C - 2 -- so they do not need
// clearing between calls.
//
// READ ADDRESSING
//   A bank i reads {fold_i, address0}, B bank j reads {fold_j, address0}.
// K_MAX is a power of two, so this concatenation *is* the offset
// fold*K_MAX + word. No adder is inferred.
//
// k_val, fold_i and fold_j MUST ALL BE STABLE while ap_start..ap_done
// is in flight: they are sampled combinationally rather than latched.
// Drive them from registers that only change while the core is idle.
module matmul_iface_rk (
    input  wire        ap_clk,
    input  wire        ap_rst,
    input  wire        ap_start,
    output wire        ap_done,
    output wire        ap_idle,
    output wire        ap_ready,

    // reduction length, held stable across a call
    input  wire [31:0] k_val,

    // fold selects, held stable across a call
    input  wire [0:0]   fold_i,
    input  wire [0:0]   fold_j,

    // operand fill port (one word per clock)
    input  wire        a_we,
    input  wire        b_we,
    input  wire [9:0]  ab_waddr,
    input  wire [31:0] ab_wdata,

    // C stays flat: R and C are still compile-time
    input  wire [2047:0] arg2_in_flat,
    output wire [2047:0] arg2_out_flat,
    output wire [63:0]   arg2_vld_flat
);

    // ---- operand RAMs ------------------------------------------
    reg [31:0] a_mem_0 [0:127];
    reg [31:0] a_q_0;
    reg [31:0] a_mem_1 [0:127];
    reg [31:0] a_q_1;
    reg [31:0] a_mem_2 [0:127];
    reg [31:0] a_q_2;
    reg [31:0] a_mem_3 [0:127];
    reg [31:0] a_q_3;
    reg [31:0] a_mem_4 [0:127];
    reg [31:0] a_q_4;
    reg [31:0] a_mem_5 [0:127];
    reg [31:0] a_q_5;
    reg [31:0] a_mem_6 [0:127];
    reg [31:0] a_q_6;
    reg [31:0] a_mem_7 [0:127];
    reg [31:0] a_q_7;

    wire [5:0] a_raddr_0;
    wire [5:0] a_raddr_1;
    wire [5:0] a_raddr_2;
    wire [5:0] a_raddr_3;
    wire [5:0] a_raddr_4;
    wire [5:0] a_raddr_5;
    wire [5:0] a_raddr_6;
    wire [5:0] a_raddr_7;

    always @(posedge ap_clk) begin
        if (a_we && ab_waddr[9:7] == 3'd0)
            a_mem_0[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        a_q_0 <= a_mem_0[{fold_i, a_raddr_0}];
    end
    always @(posedge ap_clk) begin
        if (a_we && ab_waddr[9:7] == 3'd1)
            a_mem_1[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        a_q_1 <= a_mem_1[{fold_i, a_raddr_1}];
    end
    always @(posedge ap_clk) begin
        if (a_we && ab_waddr[9:7] == 3'd2)
            a_mem_2[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        a_q_2 <= a_mem_2[{fold_i, a_raddr_2}];
    end
    always @(posedge ap_clk) begin
        if (a_we && ab_waddr[9:7] == 3'd3)
            a_mem_3[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        a_q_3 <= a_mem_3[{fold_i, a_raddr_3}];
    end
    always @(posedge ap_clk) begin
        if (a_we && ab_waddr[9:7] == 3'd4)
            a_mem_4[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        a_q_4 <= a_mem_4[{fold_i, a_raddr_4}];
    end
    always @(posedge ap_clk) begin
        if (a_we && ab_waddr[9:7] == 3'd5)
            a_mem_5[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        a_q_5 <= a_mem_5[{fold_i, a_raddr_5}];
    end
    always @(posedge ap_clk) begin
        if (a_we && ab_waddr[9:7] == 3'd6)
            a_mem_6[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        a_q_6 <= a_mem_6[{fold_i, a_raddr_6}];
    end
    always @(posedge ap_clk) begin
        if (a_we && ab_waddr[9:7] == 3'd7)
            a_mem_7[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        a_q_7 <= a_mem_7[{fold_i, a_raddr_7}];
    end

    reg [31:0] b_mem_0 [0:127];
    reg [31:0] b_q_0;
    reg [31:0] b_mem_1 [0:127];
    reg [31:0] b_q_1;
    reg [31:0] b_mem_2 [0:127];
    reg [31:0] b_q_2;
    reg [31:0] b_mem_3 [0:127];
    reg [31:0] b_q_3;
    reg [31:0] b_mem_4 [0:127];
    reg [31:0] b_q_4;
    reg [31:0] b_mem_5 [0:127];
    reg [31:0] b_q_5;
    reg [31:0] b_mem_6 [0:127];
    reg [31:0] b_q_6;
    reg [31:0] b_mem_7 [0:127];
    reg [31:0] b_q_7;

    wire [5:0] b_raddr_0;
    wire [5:0] b_raddr_1;
    wire [5:0] b_raddr_2;
    wire [5:0] b_raddr_3;
    wire [5:0] b_raddr_4;
    wire [5:0] b_raddr_5;
    wire [5:0] b_raddr_6;
    wire [5:0] b_raddr_7;

    always @(posedge ap_clk) begin
        if (b_we && ab_waddr[9:7] == 3'd0)
            b_mem_0[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        b_q_0 <= b_mem_0[{fold_j, b_raddr_0}];
    end
    always @(posedge ap_clk) begin
        if (b_we && ab_waddr[9:7] == 3'd1)
            b_mem_1[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        b_q_1 <= b_mem_1[{fold_j, b_raddr_1}];
    end
    always @(posedge ap_clk) begin
        if (b_we && ab_waddr[9:7] == 3'd2)
            b_mem_2[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        b_q_2 <= b_mem_2[{fold_j, b_raddr_2}];
    end
    always @(posedge ap_clk) begin
        if (b_we && ab_waddr[9:7] == 3'd3)
            b_mem_3[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        b_q_3 <= b_mem_3[{fold_j, b_raddr_3}];
    end
    always @(posedge ap_clk) begin
        if (b_we && ab_waddr[9:7] == 3'd4)
            b_mem_4[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        b_q_4 <= b_mem_4[{fold_j, b_raddr_4}];
    end
    always @(posedge ap_clk) begin
        if (b_we && ab_waddr[9:7] == 3'd5)
            b_mem_5[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        b_q_5 <= b_mem_5[{fold_j, b_raddr_5}];
    end
    always @(posedge ap_clk) begin
        if (b_we && ab_waddr[9:7] == 3'd6)
            b_mem_6[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        b_q_6 <= b_mem_6[{fold_j, b_raddr_6}];
    end
    always @(posedge ap_clk) begin
        if (b_we && ab_waddr[9:7] == 3'd7)
            b_mem_7[{ab_waddr[6:6], ab_waddr[5:0]}] <= ab_wdata;
        b_q_7 <= b_mem_7[{fold_j, b_raddr_7}];
    end

    // ---- C: flat in, flat out ----------------------------------
    wire [31:0] w_arg2_in_0_0 = arg2_in_flat[31:0];
    wire [31:0] w_arg2_in_0_1 = arg2_in_flat[63:32];
    wire [31:0] w_arg2_in_0_2 = arg2_in_flat[95:64];
    wire [31:0] w_arg2_in_0_3 = arg2_in_flat[127:96];
    wire [31:0] w_arg2_in_0_4 = arg2_in_flat[159:128];
    wire [31:0] w_arg2_in_0_5 = arg2_in_flat[191:160];
    wire [31:0] w_arg2_in_0_6 = arg2_in_flat[223:192];
    wire [31:0] w_arg2_in_0_7 = arg2_in_flat[255:224];
    wire [31:0] w_arg2_in_1_0 = arg2_in_flat[287:256];
    wire [31:0] w_arg2_in_1_1 = arg2_in_flat[319:288];
    wire [31:0] w_arg2_in_1_2 = arg2_in_flat[351:320];
    wire [31:0] w_arg2_in_1_3 = arg2_in_flat[383:352];
    wire [31:0] w_arg2_in_1_4 = arg2_in_flat[415:384];
    wire [31:0] w_arg2_in_1_5 = arg2_in_flat[447:416];
    wire [31:0] w_arg2_in_1_6 = arg2_in_flat[479:448];
    wire [31:0] w_arg2_in_1_7 = arg2_in_flat[511:480];
    wire [31:0] w_arg2_in_2_0 = arg2_in_flat[543:512];
    wire [31:0] w_arg2_in_2_1 = arg2_in_flat[575:544];
    wire [31:0] w_arg2_in_2_2 = arg2_in_flat[607:576];
    wire [31:0] w_arg2_in_2_3 = arg2_in_flat[639:608];
    wire [31:0] w_arg2_in_2_4 = arg2_in_flat[671:640];
    wire [31:0] w_arg2_in_2_5 = arg2_in_flat[703:672];
    wire [31:0] w_arg2_in_2_6 = arg2_in_flat[735:704];
    wire [31:0] w_arg2_in_2_7 = arg2_in_flat[767:736];
    wire [31:0] w_arg2_in_3_0 = arg2_in_flat[799:768];
    wire [31:0] w_arg2_in_3_1 = arg2_in_flat[831:800];
    wire [31:0] w_arg2_in_3_2 = arg2_in_flat[863:832];
    wire [31:0] w_arg2_in_3_3 = arg2_in_flat[895:864];
    wire [31:0] w_arg2_in_3_4 = arg2_in_flat[927:896];
    wire [31:0] w_arg2_in_3_5 = arg2_in_flat[959:928];
    wire [31:0] w_arg2_in_3_6 = arg2_in_flat[991:960];
    wire [31:0] w_arg2_in_3_7 = arg2_in_flat[1023:992];
    wire [31:0] w_arg2_in_4_0 = arg2_in_flat[1055:1024];
    wire [31:0] w_arg2_in_4_1 = arg2_in_flat[1087:1056];
    wire [31:0] w_arg2_in_4_2 = arg2_in_flat[1119:1088];
    wire [31:0] w_arg2_in_4_3 = arg2_in_flat[1151:1120];
    wire [31:0] w_arg2_in_4_4 = arg2_in_flat[1183:1152];
    wire [31:0] w_arg2_in_4_5 = arg2_in_flat[1215:1184];
    wire [31:0] w_arg2_in_4_6 = arg2_in_flat[1247:1216];
    wire [31:0] w_arg2_in_4_7 = arg2_in_flat[1279:1248];
    wire [31:0] w_arg2_in_5_0 = arg2_in_flat[1311:1280];
    wire [31:0] w_arg2_in_5_1 = arg2_in_flat[1343:1312];
    wire [31:0] w_arg2_in_5_2 = arg2_in_flat[1375:1344];
    wire [31:0] w_arg2_in_5_3 = arg2_in_flat[1407:1376];
    wire [31:0] w_arg2_in_5_4 = arg2_in_flat[1439:1408];
    wire [31:0] w_arg2_in_5_5 = arg2_in_flat[1471:1440];
    wire [31:0] w_arg2_in_5_6 = arg2_in_flat[1503:1472];
    wire [31:0] w_arg2_in_5_7 = arg2_in_flat[1535:1504];
    wire [31:0] w_arg2_in_6_0 = arg2_in_flat[1567:1536];
    wire [31:0] w_arg2_in_6_1 = arg2_in_flat[1599:1568];
    wire [31:0] w_arg2_in_6_2 = arg2_in_flat[1631:1600];
    wire [31:0] w_arg2_in_6_3 = arg2_in_flat[1663:1632];
    wire [31:0] w_arg2_in_6_4 = arg2_in_flat[1695:1664];
    wire [31:0] w_arg2_in_6_5 = arg2_in_flat[1727:1696];
    wire [31:0] w_arg2_in_6_6 = arg2_in_flat[1759:1728];
    wire [31:0] w_arg2_in_6_7 = arg2_in_flat[1791:1760];
    wire [31:0] w_arg2_in_7_0 = arg2_in_flat[1823:1792];
    wire [31:0] w_arg2_in_7_1 = arg2_in_flat[1855:1824];
    wire [31:0] w_arg2_in_7_2 = arg2_in_flat[1887:1856];
    wire [31:0] w_arg2_in_7_3 = arg2_in_flat[1919:1888];
    wire [31:0] w_arg2_in_7_4 = arg2_in_flat[1951:1920];
    wire [31:0] w_arg2_in_7_5 = arg2_in_flat[1983:1952];
    wire [31:0] w_arg2_in_7_6 = arg2_in_flat[2015:1984];
    wire [31:0] w_arg2_in_7_7 = arg2_in_flat[2047:2016];

    wire [31:0] w_arg2o   [0:63];
    wire        w_arg2vld [0:63];

    assign arg2_out_flat[31:0] = w_arg2o[0];
    assign arg2_vld_flat[0] = w_arg2vld[0];
    assign arg2_out_flat[63:32] = w_arg2o[1];
    assign arg2_vld_flat[1] = w_arg2vld[1];
    assign arg2_out_flat[95:64] = w_arg2o[2];
    assign arg2_vld_flat[2] = w_arg2vld[2];
    assign arg2_out_flat[127:96] = w_arg2o[3];
    assign arg2_vld_flat[3] = w_arg2vld[3];
    assign arg2_out_flat[159:128] = w_arg2o[4];
    assign arg2_vld_flat[4] = w_arg2vld[4];
    assign arg2_out_flat[191:160] = w_arg2o[5];
    assign arg2_vld_flat[5] = w_arg2vld[5];
    assign arg2_out_flat[223:192] = w_arg2o[6];
    assign arg2_vld_flat[6] = w_arg2vld[6];
    assign arg2_out_flat[255:224] = w_arg2o[7];
    assign arg2_vld_flat[7] = w_arg2vld[7];
    assign arg2_out_flat[287:256] = w_arg2o[8];
    assign arg2_vld_flat[8] = w_arg2vld[8];
    assign arg2_out_flat[319:288] = w_arg2o[9];
    assign arg2_vld_flat[9] = w_arg2vld[9];
    assign arg2_out_flat[351:320] = w_arg2o[10];
    assign arg2_vld_flat[10] = w_arg2vld[10];
    assign arg2_out_flat[383:352] = w_arg2o[11];
    assign arg2_vld_flat[11] = w_arg2vld[11];
    assign arg2_out_flat[415:384] = w_arg2o[12];
    assign arg2_vld_flat[12] = w_arg2vld[12];
    assign arg2_out_flat[447:416] = w_arg2o[13];
    assign arg2_vld_flat[13] = w_arg2vld[13];
    assign arg2_out_flat[479:448] = w_arg2o[14];
    assign arg2_vld_flat[14] = w_arg2vld[14];
    assign arg2_out_flat[511:480] = w_arg2o[15];
    assign arg2_vld_flat[15] = w_arg2vld[15];
    assign arg2_out_flat[543:512] = w_arg2o[16];
    assign arg2_vld_flat[16] = w_arg2vld[16];
    assign arg2_out_flat[575:544] = w_arg2o[17];
    assign arg2_vld_flat[17] = w_arg2vld[17];
    assign arg2_out_flat[607:576] = w_arg2o[18];
    assign arg2_vld_flat[18] = w_arg2vld[18];
    assign arg2_out_flat[639:608] = w_arg2o[19];
    assign arg2_vld_flat[19] = w_arg2vld[19];
    assign arg2_out_flat[671:640] = w_arg2o[20];
    assign arg2_vld_flat[20] = w_arg2vld[20];
    assign arg2_out_flat[703:672] = w_arg2o[21];
    assign arg2_vld_flat[21] = w_arg2vld[21];
    assign arg2_out_flat[735:704] = w_arg2o[22];
    assign arg2_vld_flat[22] = w_arg2vld[22];
    assign arg2_out_flat[767:736] = w_arg2o[23];
    assign arg2_vld_flat[23] = w_arg2vld[23];
    assign arg2_out_flat[799:768] = w_arg2o[24];
    assign arg2_vld_flat[24] = w_arg2vld[24];
    assign arg2_out_flat[831:800] = w_arg2o[25];
    assign arg2_vld_flat[25] = w_arg2vld[25];
    assign arg2_out_flat[863:832] = w_arg2o[26];
    assign arg2_vld_flat[26] = w_arg2vld[26];
    assign arg2_out_flat[895:864] = w_arg2o[27];
    assign arg2_vld_flat[27] = w_arg2vld[27];
    assign arg2_out_flat[927:896] = w_arg2o[28];
    assign arg2_vld_flat[28] = w_arg2vld[28];
    assign arg2_out_flat[959:928] = w_arg2o[29];
    assign arg2_vld_flat[29] = w_arg2vld[29];
    assign arg2_out_flat[991:960] = w_arg2o[30];
    assign arg2_vld_flat[30] = w_arg2vld[30];
    assign arg2_out_flat[1023:992] = w_arg2o[31];
    assign arg2_vld_flat[31] = w_arg2vld[31];
    assign arg2_out_flat[1055:1024] = w_arg2o[32];
    assign arg2_vld_flat[32] = w_arg2vld[32];
    assign arg2_out_flat[1087:1056] = w_arg2o[33];
    assign arg2_vld_flat[33] = w_arg2vld[33];
    assign arg2_out_flat[1119:1088] = w_arg2o[34];
    assign arg2_vld_flat[34] = w_arg2vld[34];
    assign arg2_out_flat[1151:1120] = w_arg2o[35];
    assign arg2_vld_flat[35] = w_arg2vld[35];
    assign arg2_out_flat[1183:1152] = w_arg2o[36];
    assign arg2_vld_flat[36] = w_arg2vld[36];
    assign arg2_out_flat[1215:1184] = w_arg2o[37];
    assign arg2_vld_flat[37] = w_arg2vld[37];
    assign arg2_out_flat[1247:1216] = w_arg2o[38];
    assign arg2_vld_flat[38] = w_arg2vld[38];
    assign arg2_out_flat[1279:1248] = w_arg2o[39];
    assign arg2_vld_flat[39] = w_arg2vld[39];
    assign arg2_out_flat[1311:1280] = w_arg2o[40];
    assign arg2_vld_flat[40] = w_arg2vld[40];
    assign arg2_out_flat[1343:1312] = w_arg2o[41];
    assign arg2_vld_flat[41] = w_arg2vld[41];
    assign arg2_out_flat[1375:1344] = w_arg2o[42];
    assign arg2_vld_flat[42] = w_arg2vld[42];
    assign arg2_out_flat[1407:1376] = w_arg2o[43];
    assign arg2_vld_flat[43] = w_arg2vld[43];
    assign arg2_out_flat[1439:1408] = w_arg2o[44];
    assign arg2_vld_flat[44] = w_arg2vld[44];
    assign arg2_out_flat[1471:1440] = w_arg2o[45];
    assign arg2_vld_flat[45] = w_arg2vld[45];
    assign arg2_out_flat[1503:1472] = w_arg2o[46];
    assign arg2_vld_flat[46] = w_arg2vld[46];
    assign arg2_out_flat[1535:1504] = w_arg2o[47];
    assign arg2_vld_flat[47] = w_arg2vld[47];
    assign arg2_out_flat[1567:1536] = w_arg2o[48];
    assign arg2_vld_flat[48] = w_arg2vld[48];
    assign arg2_out_flat[1599:1568] = w_arg2o[49];
    assign arg2_vld_flat[49] = w_arg2vld[49];
    assign arg2_out_flat[1631:1600] = w_arg2o[50];
    assign arg2_vld_flat[50] = w_arg2vld[50];
    assign arg2_out_flat[1663:1632] = w_arg2o[51];
    assign arg2_vld_flat[51] = w_arg2vld[51];
    assign arg2_out_flat[1695:1664] = w_arg2o[52];
    assign arg2_vld_flat[52] = w_arg2vld[52];
    assign arg2_out_flat[1727:1696] = w_arg2o[53];
    assign arg2_vld_flat[53] = w_arg2vld[53];
    assign arg2_out_flat[1759:1728] = w_arg2o[54];
    assign arg2_vld_flat[54] = w_arg2vld[54];
    assign arg2_out_flat[1791:1760] = w_arg2o[55];
    assign arg2_vld_flat[55] = w_arg2vld[55];
    assign arg2_out_flat[1823:1792] = w_arg2o[56];
    assign arg2_vld_flat[56] = w_arg2vld[56];
    assign arg2_out_flat[1855:1824] = w_arg2o[57];
    assign arg2_vld_flat[57] = w_arg2vld[57];
    assign arg2_out_flat[1887:1856] = w_arg2o[58];
    assign arg2_vld_flat[58] = w_arg2vld[58];
    assign arg2_out_flat[1919:1888] = w_arg2o[59];
    assign arg2_vld_flat[59] = w_arg2vld[59];
    assign arg2_out_flat[1951:1920] = w_arg2o[60];
    assign arg2_vld_flat[60] = w_arg2vld[60];
    assign arg2_out_flat[1983:1952] = w_arg2o[61];
    assign arg2_vld_flat[61] = w_arg2vld[61];
    assign arg2_out_flat[2015:1984] = w_arg2o[62];
    assign arg2_vld_flat[62] = w_arg2vld[62];
    assign arg2_out_flat[2047:2016] = w_arg2o[63];
    assign arg2_vld_flat[63] = w_arg2vld[63];

    // ---- core --------------------------------------------------
    matmul_8x8x8 u_matmul (
        .ap_clk(ap_clk),
        .ap_rst(ap_rst),
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        .K(k_val),
        .A_0_address0(a_raddr_0),
        .A_0_ce0(),
        .A_0_q0(a_q_0),
        .A_1_address0(a_raddr_1),
        .A_1_ce0(),
        .A_1_q0(a_q_1),
        .A_2_address0(a_raddr_2),
        .A_2_ce0(),
        .A_2_q0(a_q_2),
        .A_3_address0(a_raddr_3),
        .A_3_ce0(),
        .A_3_q0(a_q_3),
        .A_4_address0(a_raddr_4),
        .A_4_ce0(),
        .A_4_q0(a_q_4),
        .A_5_address0(a_raddr_5),
        .A_5_ce0(),
        .A_5_q0(a_q_5),
        .A_6_address0(a_raddr_6),
        .A_6_ce0(),
        .A_6_q0(a_q_6),
        .A_7_address0(a_raddr_7),
        .A_7_ce0(),
        .A_7_q0(a_q_7),
        .B_0_address0(b_raddr_0),
        .B_0_ce0(),
        .B_0_q0(b_q_0),
        .B_1_address0(b_raddr_1),
        .B_1_ce0(),
        .B_1_q0(b_q_1),
        .B_2_address0(b_raddr_2),
        .B_2_ce0(),
        .B_2_q0(b_q_2),
        .B_3_address0(b_raddr_3),
        .B_3_ce0(),
        .B_3_q0(b_q_3),
        .B_4_address0(b_raddr_4),
        .B_4_ce0(),
        .B_4_q0(b_q_4),
        .B_5_address0(b_raddr_5),
        .B_5_ce0(),
        .B_5_q0(b_q_5),
        .B_6_address0(b_raddr_6),
        .B_6_ce0(),
        .B_6_q0(b_q_6),
        .B_7_address0(b_raddr_7),
        .B_7_ce0(),
        .B_7_q0(b_q_7),
        .Cinout_0_0_i(w_arg2_in_0_0),
        .Cinout_0_0_o(w_arg2o[0]),
        .Cinout_0_0_o_ap_vld(w_arg2vld[0]),
        .Cinout_0_1_i(w_arg2_in_0_1),
        .Cinout_0_1_o(w_arg2o[1]),
        .Cinout_0_1_o_ap_vld(w_arg2vld[1]),
        .Cinout_0_2_i(w_arg2_in_0_2),
        .Cinout_0_2_o(w_arg2o[2]),
        .Cinout_0_2_o_ap_vld(w_arg2vld[2]),
        .Cinout_0_3_i(w_arg2_in_0_3),
        .Cinout_0_3_o(w_arg2o[3]),
        .Cinout_0_3_o_ap_vld(w_arg2vld[3]),
        .Cinout_0_4_i(w_arg2_in_0_4),
        .Cinout_0_4_o(w_arg2o[4]),
        .Cinout_0_4_o_ap_vld(w_arg2vld[4]),
        .Cinout_0_5_i(w_arg2_in_0_5),
        .Cinout_0_5_o(w_arg2o[5]),
        .Cinout_0_5_o_ap_vld(w_arg2vld[5]),
        .Cinout_0_6_i(w_arg2_in_0_6),
        .Cinout_0_6_o(w_arg2o[6]),
        .Cinout_0_6_o_ap_vld(w_arg2vld[6]),
        .Cinout_0_7_i(w_arg2_in_0_7),
        .Cinout_0_7_o(w_arg2o[7]),
        .Cinout_0_7_o_ap_vld(w_arg2vld[7]),
        .Cinout_1_0_i(w_arg2_in_1_0),
        .Cinout_1_0_o(w_arg2o[8]),
        .Cinout_1_0_o_ap_vld(w_arg2vld[8]),
        .Cinout_1_1_i(w_arg2_in_1_1),
        .Cinout_1_1_o(w_arg2o[9]),
        .Cinout_1_1_o_ap_vld(w_arg2vld[9]),
        .Cinout_1_2_i(w_arg2_in_1_2),
        .Cinout_1_2_o(w_arg2o[10]),
        .Cinout_1_2_o_ap_vld(w_arg2vld[10]),
        .Cinout_1_3_i(w_arg2_in_1_3),
        .Cinout_1_3_o(w_arg2o[11]),
        .Cinout_1_3_o_ap_vld(w_arg2vld[11]),
        .Cinout_1_4_i(w_arg2_in_1_4),
        .Cinout_1_4_o(w_arg2o[12]),
        .Cinout_1_4_o_ap_vld(w_arg2vld[12]),
        .Cinout_1_5_i(w_arg2_in_1_5),
        .Cinout_1_5_o(w_arg2o[13]),
        .Cinout_1_5_o_ap_vld(w_arg2vld[13]),
        .Cinout_1_6_i(w_arg2_in_1_6),
        .Cinout_1_6_o(w_arg2o[14]),
        .Cinout_1_6_o_ap_vld(w_arg2vld[14]),
        .Cinout_1_7_i(w_arg2_in_1_7),
        .Cinout_1_7_o(w_arg2o[15]),
        .Cinout_1_7_o_ap_vld(w_arg2vld[15]),
        .Cinout_2_0_i(w_arg2_in_2_0),
        .Cinout_2_0_o(w_arg2o[16]),
        .Cinout_2_0_o_ap_vld(w_arg2vld[16]),
        .Cinout_2_1_i(w_arg2_in_2_1),
        .Cinout_2_1_o(w_arg2o[17]),
        .Cinout_2_1_o_ap_vld(w_arg2vld[17]),
        .Cinout_2_2_i(w_arg2_in_2_2),
        .Cinout_2_2_o(w_arg2o[18]),
        .Cinout_2_2_o_ap_vld(w_arg2vld[18]),
        .Cinout_2_3_i(w_arg2_in_2_3),
        .Cinout_2_3_o(w_arg2o[19]),
        .Cinout_2_3_o_ap_vld(w_arg2vld[19]),
        .Cinout_2_4_i(w_arg2_in_2_4),
        .Cinout_2_4_o(w_arg2o[20]),
        .Cinout_2_4_o_ap_vld(w_arg2vld[20]),
        .Cinout_2_5_i(w_arg2_in_2_5),
        .Cinout_2_5_o(w_arg2o[21]),
        .Cinout_2_5_o_ap_vld(w_arg2vld[21]),
        .Cinout_2_6_i(w_arg2_in_2_6),
        .Cinout_2_6_o(w_arg2o[22]),
        .Cinout_2_6_o_ap_vld(w_arg2vld[22]),
        .Cinout_2_7_i(w_arg2_in_2_7),
        .Cinout_2_7_o(w_arg2o[23]),
        .Cinout_2_7_o_ap_vld(w_arg2vld[23]),
        .Cinout_3_0_i(w_arg2_in_3_0),
        .Cinout_3_0_o(w_arg2o[24]),
        .Cinout_3_0_o_ap_vld(w_arg2vld[24]),
        .Cinout_3_1_i(w_arg2_in_3_1),
        .Cinout_3_1_o(w_arg2o[25]),
        .Cinout_3_1_o_ap_vld(w_arg2vld[25]),
        .Cinout_3_2_i(w_arg2_in_3_2),
        .Cinout_3_2_o(w_arg2o[26]),
        .Cinout_3_2_o_ap_vld(w_arg2vld[26]),
        .Cinout_3_3_i(w_arg2_in_3_3),
        .Cinout_3_3_o(w_arg2o[27]),
        .Cinout_3_3_o_ap_vld(w_arg2vld[27]),
        .Cinout_3_4_i(w_arg2_in_3_4),
        .Cinout_3_4_o(w_arg2o[28]),
        .Cinout_3_4_o_ap_vld(w_arg2vld[28]),
        .Cinout_3_5_i(w_arg2_in_3_5),
        .Cinout_3_5_o(w_arg2o[29]),
        .Cinout_3_5_o_ap_vld(w_arg2vld[29]),
        .Cinout_3_6_i(w_arg2_in_3_6),
        .Cinout_3_6_o(w_arg2o[30]),
        .Cinout_3_6_o_ap_vld(w_arg2vld[30]),
        .Cinout_3_7_i(w_arg2_in_3_7),
        .Cinout_3_7_o(w_arg2o[31]),
        .Cinout_3_7_o_ap_vld(w_arg2vld[31]),
        .Cinout_4_0_i(w_arg2_in_4_0),
        .Cinout_4_0_o(w_arg2o[32]),
        .Cinout_4_0_o_ap_vld(w_arg2vld[32]),
        .Cinout_4_1_i(w_arg2_in_4_1),
        .Cinout_4_1_o(w_arg2o[33]),
        .Cinout_4_1_o_ap_vld(w_arg2vld[33]),
        .Cinout_4_2_i(w_arg2_in_4_2),
        .Cinout_4_2_o(w_arg2o[34]),
        .Cinout_4_2_o_ap_vld(w_arg2vld[34]),
        .Cinout_4_3_i(w_arg2_in_4_3),
        .Cinout_4_3_o(w_arg2o[35]),
        .Cinout_4_3_o_ap_vld(w_arg2vld[35]),
        .Cinout_4_4_i(w_arg2_in_4_4),
        .Cinout_4_4_o(w_arg2o[36]),
        .Cinout_4_4_o_ap_vld(w_arg2vld[36]),
        .Cinout_4_5_i(w_arg2_in_4_5),
        .Cinout_4_5_o(w_arg2o[37]),
        .Cinout_4_5_o_ap_vld(w_arg2vld[37]),
        .Cinout_4_6_i(w_arg2_in_4_6),
        .Cinout_4_6_o(w_arg2o[38]),
        .Cinout_4_6_o_ap_vld(w_arg2vld[38]),
        .Cinout_4_7_i(w_arg2_in_4_7),
        .Cinout_4_7_o(w_arg2o[39]),
        .Cinout_4_7_o_ap_vld(w_arg2vld[39]),
        .Cinout_5_0_i(w_arg2_in_5_0),
        .Cinout_5_0_o(w_arg2o[40]),
        .Cinout_5_0_o_ap_vld(w_arg2vld[40]),
        .Cinout_5_1_i(w_arg2_in_5_1),
        .Cinout_5_1_o(w_arg2o[41]),
        .Cinout_5_1_o_ap_vld(w_arg2vld[41]),
        .Cinout_5_2_i(w_arg2_in_5_2),
        .Cinout_5_2_o(w_arg2o[42]),
        .Cinout_5_2_o_ap_vld(w_arg2vld[42]),
        .Cinout_5_3_i(w_arg2_in_5_3),
        .Cinout_5_3_o(w_arg2o[43]),
        .Cinout_5_3_o_ap_vld(w_arg2vld[43]),
        .Cinout_5_4_i(w_arg2_in_5_4),
        .Cinout_5_4_o(w_arg2o[44]),
        .Cinout_5_4_o_ap_vld(w_arg2vld[44]),
        .Cinout_5_5_i(w_arg2_in_5_5),
        .Cinout_5_5_o(w_arg2o[45]),
        .Cinout_5_5_o_ap_vld(w_arg2vld[45]),
        .Cinout_5_6_i(w_arg2_in_5_6),
        .Cinout_5_6_o(w_arg2o[46]),
        .Cinout_5_6_o_ap_vld(w_arg2vld[46]),
        .Cinout_5_7_i(w_arg2_in_5_7),
        .Cinout_5_7_o(w_arg2o[47]),
        .Cinout_5_7_o_ap_vld(w_arg2vld[47]),
        .Cinout_6_0_i(w_arg2_in_6_0),
        .Cinout_6_0_o(w_arg2o[48]),
        .Cinout_6_0_o_ap_vld(w_arg2vld[48]),
        .Cinout_6_1_i(w_arg2_in_6_1),
        .Cinout_6_1_o(w_arg2o[49]),
        .Cinout_6_1_o_ap_vld(w_arg2vld[49]),
        .Cinout_6_2_i(w_arg2_in_6_2),
        .Cinout_6_2_o(w_arg2o[50]),
        .Cinout_6_2_o_ap_vld(w_arg2vld[50]),
        .Cinout_6_3_i(w_arg2_in_6_3),
        .Cinout_6_3_o(w_arg2o[51]),
        .Cinout_6_3_o_ap_vld(w_arg2vld[51]),
        .Cinout_6_4_i(w_arg2_in_6_4),
        .Cinout_6_4_o(w_arg2o[52]),
        .Cinout_6_4_o_ap_vld(w_arg2vld[52]),
        .Cinout_6_5_i(w_arg2_in_6_5),
        .Cinout_6_5_o(w_arg2o[53]),
        .Cinout_6_5_o_ap_vld(w_arg2vld[53]),
        .Cinout_6_6_i(w_arg2_in_6_6),
        .Cinout_6_6_o(w_arg2o[54]),
        .Cinout_6_6_o_ap_vld(w_arg2vld[54]),
        .Cinout_6_7_i(w_arg2_in_6_7),
        .Cinout_6_7_o(w_arg2o[55]),
        .Cinout_6_7_o_ap_vld(w_arg2vld[55]),
        .Cinout_7_0_i(w_arg2_in_7_0),
        .Cinout_7_0_o(w_arg2o[56]),
        .Cinout_7_0_o_ap_vld(w_arg2vld[56]),
        .Cinout_7_1_i(w_arg2_in_7_1),
        .Cinout_7_1_o(w_arg2o[57]),
        .Cinout_7_1_o_ap_vld(w_arg2vld[57]),
        .Cinout_7_2_i(w_arg2_in_7_2),
        .Cinout_7_2_o(w_arg2o[58]),
        .Cinout_7_2_o_ap_vld(w_arg2vld[58]),
        .Cinout_7_3_i(w_arg2_in_7_3),
        .Cinout_7_3_o(w_arg2o[59]),
        .Cinout_7_3_o_ap_vld(w_arg2vld[59]),
        .Cinout_7_4_i(w_arg2_in_7_4),
        .Cinout_7_4_o(w_arg2o[60]),
        .Cinout_7_4_o_ap_vld(w_arg2vld[60]),
        .Cinout_7_5_i(w_arg2_in_7_5),
        .Cinout_7_5_o(w_arg2o[61]),
        .Cinout_7_5_o_ap_vld(w_arg2vld[61]),
        .Cinout_7_6_i(w_arg2_in_7_6),
        .Cinout_7_6_o(w_arg2o[62]),
        .Cinout_7_6_o_ap_vld(w_arg2vld[62]),
        .Cinout_7_7_i(w_arg2_in_7_7),
        .Cinout_7_7_o(w_arg2o[63]),
        .Cinout_7_7_o_ap_vld(w_arg2vld[63])
    );

endmodule
