#include "design.h"
#ifndef __SYNTHESIS__
#include <cstdio>
#endif

static_assert(
    TS_MIN == 1 + R + C - 2,
    "TS_MIN stale"
);

static_assert(
    TS_MAX == K_MAX + R + C - 2,
    "TS_MAX stale"
);

static_assert(
    TS_AVG == K_MAX / 2 + R + C - 2,
    "TS_AVG stale"
);


/*
 * Stage 1
 *
 * Generate one already-skewed input beat per cycle.
 *
 * K is logically divided into FOLD_K-sized folds:
 *
 *   fold 0 : k = 0  .. 7
 *   fold 1 : k = 8  .. 15
 *   ...
 *
 * However, there is no stop between folds.
 */
static void produce_beats(
    data_t A[R][K_MAX],
    data_t B[K_MAX][C],
    hls::stream<systolic_beat_t> &beat_stream,
    int k_len
)
{
#pragma HLS INLINE off

    const int time_steps =
        k_len + R + C - 2;

produce_loop:
    for (int t = 0; t < time_steps; ++t) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=TS_MIN max=TS_MAX avg=TS_AVG

#ifndef __SYNTHESIS__
        if (t < k_len) {
            int fold = t / FOLD_K;
            int local_k = t % FOLD_K;

            std::printf(
                "[PRODUCE] t=%2d  global_k=%2d  fold=%d  local_k=%d\n",
                t, t, fold, local_k
            );
        } else {
            std::printf(
                "[PRODUCE] t=%2d  drain/fill beat\n",
                t
            );
        }
#endif

        systolic_beat_t beat;

    produce_a:
        for (int i = 0; i < R; ++i) {
#pragma HLS UNROLL

            const int global_k = t - i;

            if (global_k >= 0 &&
                global_k < k_len)
            {
                /*
                 * Explicit logical fold decomposition.
                 */
                const int fold =
                    global_k / FOLD_K;

                const int local_k =
                    global_k % FOLD_K;

                const int k =
                    fold * FOLD_K + local_k;

                beat.a_edge[i] =
                    A[i][k];
            }
            else {
                beat.a_edge[i] =
                    (data_t)0;
            }
        }

    produce_b:
        for (int j = 0; j < C; ++j) {
#pragma HLS UNROLL

            const int global_k = t - j;

            if (global_k >= 0 &&
                global_k < k_len)
            {
                const int fold =
                    global_k / FOLD_K;

                const int local_k =
                    global_k % FOLD_K;

                const int k =
                    fold * FOLD_K + local_k;

                beat.b_edge[j] =
                    B[k][j];
            }
            else {
                beat.b_edge[j] =
                    (data_t)0;
            }
        }

        beat_stream.write(beat);
    }
}


/*
 * Stage 2
 *
 * Consume one beat per cycle and move operands through
 * the systolic array.
 *
 * No accumulator reset occurs at fold boundaries.
 */
static void systolic_compute(
    hls::stream<systolic_beat_t> &beat_stream,
    data_t Cinout[R][C],
    int k_len
)
{
#pragma HLS INLINE off

    acc_t acc[R][C];

    data_t a_reg[R][C];
    data_t b_reg[R][C];

#pragma HLS ARRAY_PARTITION variable=acc   complete dim=0
#pragma HLS ARRAY_PARTITION variable=a_reg complete dim=0
#pragma HLS ARRAY_PARTITION variable=b_reg complete dim=0
#pragma HLS ARRAY_PARTITION variable=Cinout complete dim=0


/*
 * Initialise exactly once for the entire K reduction.
 */
init_i:
    for (int i = 0; i < R; ++i) {
#pragma HLS UNROLL

    init_j:
        for (int j = 0; j < C; ++j) {
#pragma HLS UNROLL

            acc[i][j] =
                Cinout[i][j];

            a_reg[i][j] =
                (data_t)0;

            b_reg[i][j] =
                (data_t)0;
        }
    }


    const int time_steps =
        k_len + R + C - 2;


/*
 * One loop iteration = one systolic beat.
 *
 * Fold boundaries do not terminate this loop.
 */
compute_loop:
    for (int t = 0; t < time_steps; ++t) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=TS_MIN max=TS_MAX avg=TS_AVG

        systolic_beat_t beat =
            beat_stream.read();

#ifndef __SYNTHESIS__
        if (t < k_len) {
            int fold = t / FOLD_K;
            int local_k = t % FOLD_K;

            std::printf(
                "[COMPUTE] t=%2d  logical_k=%2d  fold=%d  local_k=%d\n",
                t, t, fold, local_k
            );
        } else {
            std::printf(
                "[COMPUTE] t=%2d  drain beat\n",
                t
            );
        }
#endif

    pe_i:
        for (int i = R - 1; i >= 0; --i) {
#pragma HLS UNROLL

        pe_j:
            for (int j = C - 1; j >= 0; --j) {
#pragma HLS UNROLL

                data_t a_in;

                if (j == 0) {
                    /*
                     * West edge.
                     * Skew already generated by producer.
                     */
                    a_in =
                        beat.a_edge[i];
                }
                else {
                    /*
                     * Previous beat from left PE.
                     */
                    a_in =
                        a_reg[i][j - 1];
                }


                data_t b_in;

                if (i == 0) {
                    /*
                     * North edge.
                     */
                    b_in =
                        beat.b_edge[j];
                }
                else {
                    /*
                     * Previous beat from upper PE.
                     */
                    b_in =
                        b_reg[i - 1][j];
                }


                /*
                 * Output-stationary accumulation.
                 *
                 * fold0 → fold1 does NOT reset acc.
                 */
                acc[i][j] +=
                    a_in * b_in;


                /*
                 * Forward operands to downstream PEs
                 * on the next systolic beat.
                 */
                a_reg[i][j] =
                    a_in;

                b_reg[i][j] =
                    b_in;
            }
        }
    }


/*
 * Drain result exactly once after all folds.
 */
drain_i:
    for (int i = 0; i < R; ++i) {
#pragma HLS UNROLL

    drain_j:
        for (int j = 0; j < C; ++j) {
#pragma HLS UNROLL

            Cinout[i][j] =
                acc[i][j];
        }
    }
}


/*
 * Top-level fold-pipelined kernel.
 */
void matmul_8x8_fold_pipelined(
    data_t A[R][K_MAX],
    data_t B[K_MAX][C],
    data_t Cinout[R][C],
    int K
)
{
#pragma HLS ARRAY_PARTITION variable=A       complete dim=1
#pragma HLS ARRAY_PARTITION variable=B       complete dim=2
#pragma HLS ARRAY_PARTITION variable=Cinout  complete dim=0

    const int k_len =
        (K < 0)
            ? 0
            : ((K > K_MAX)
                ? K_MAX
                : K);


    /*
     * FIFO between fold producer and systolic consumer.
     */
    hls::stream<systolic_beat_t> beat_stream;

#pragma HLS STREAM variable=beat_stream depth=4


    /*
     * This is the important part.
     *
     * produce_beats() and systolic_compute()
     * become independent concurrent HLS processes.
     */
#pragma HLS DATAFLOW

    produce_beats(
        A,
        B,
        beat_stream,
        k_len
    );

    systolic_compute(
        beat_stream,
        Cinout,
        k_len
    );
}